#!/bin/sh

# unlocking hotplug
touch /var/run/hotplug

# Create mtab file
touch /var/bewan/mtab

# run previous hotplug event
EVTS=`ls /var/hotplug.d | sort`
if [ "$EVTS" != "" ]; then
	for i in $EVTS; do
		sh /var/hotplug.d/$i > /dev/console 2>/dev/console
	done
fi
