#!/bin/sh

start_wlmngr()
{
  /bin/wlmngr
  base_exit_critical 'bcmwl-init'
  
  for lanid in `ls $LAND`; do
    for intf in `cat $LAND/$lanid/intfs`; do
        LANID=$lanid
        . /etc/bewan/lib/lan
        add_interface_to_lan_bridge all $LANID
    done
  done

  /bin/wlmngr
}

_wl_error=0
for comp in eapd nas wlmngr; do
  if ! which $comp > /dev/null; then
    base_log "$comp is missing, bcm wireless driver is not properly built" debug
    _wl_error=1
  fi
done
[ "$_wl_error" = 1 ] && return

start_wlmngr &
