#!/bin/sh
# vim: set ts=2 sw=2 et:

ACTION=${1:-}
WHEN=${2:-}
MOUNTPOINT=${3:-}

# load setparam
. /etc/bewan/init.d/setparam

base_log "Entering storage superdlna." debug

unmount_superdlna()
{
	local superdlna_dir=${Services_SuperDLNA_Path:-"/var/bewan/superdlna.d"}
	local pipe_unmount="${superdlna_dir}/unmount"
	local myaction="$ACTION"
	
	# We only need to do something before mount/umount operations have been done
	# So only deal with 'pre' actions and with mountpoints not empty
	if [ "${Services_SuperDLNA_Enable:-}" != 1 -o "$WHEN" != "pre" -o "$MOUNTPOINT" = "" ] ; then
		myaction="drop-$ACTION"
	fi

#  base_log  "$pipe_unmount" debug

	case "$myaction" in
		remove)
		if [ -p $pipe_unmount ]; then
			base_log "Print in pipe ${pipe_unmount} : $MOUNTPOINT" debug
			echo "$MOUNTPOINT" >> ${pipe_unmount}
		fi
	# do nothing
	;;
	*)
	base_log "Action $myaction $WHEN $MOUNTPOINT dropped" debug
	;;
esac
}

#execute
unmount_superdlna
