#!/bin/sh

# Parse all vendor options
while [ "${1:-}" != "" ]
do
	local code=${1:-}
	shift 1
	local value=${1:-}
	shift 1

	# Code 1 : ACS URL
	if [ "$code" = "1" ]; then
		if [ "$value" != "" ]; then
			echo $value
		fi
	fi
done

