#! /bin/sh

#PATH=/sbin:/bin
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

mount -t proc proc /proc
#/bin/mount -a
#/sbin/inetd
SKIP_PROFILE=0 sh /etc/profile


# Mount file systems if not already mounted by BSP startup
test -z "$(mount -t sysfs)" && mount -t sysfs sysfs /sys
test -z "$(mount -t tmpfs | grep /var)" && mount -t tmpfs -o size=8M shm /var
mkdir -p /var/bewan

# Create /dev in ram
test -z "$(mount -t tmpfs | grep /dev)" && mount -t tmpfs -o size=128k shm /dev

# Start mdev if not already done by BSP startup
if test -z $(cat /proc/sys/kernel/hotplug | grep mdev); then
  cat /etc/bewan/mdev/* > /var/bewan/mdev.conf
  echo "/sbin/mdev" > /proc/sys/kernel/hotplug
  mdev -s
fi

# If config partition is called nvram, mount it as a JFFS2 filesystem
cat /proc/mtd | grep mtd2 | grep Nvram >/dev/null
if  [ $? = 0 ]; then
	mount -t jffs2 -o rw /dev/mtdblock2 /nvram
	if  [ $? != 0 ]; then
		# If mount failed, erase it, then remount
		# (jffs2 will take care of it)
		flash_erase /dev/mtd2 0 0
		mount -t jffs2 -o rw /dev/mtdblock2 /nvram
	fi
fi

start-stop-daemon -S -b -x /etc/bewan/rc

