#!/bin/sh
# /etc/bewan/ip-down-lan.d/K10nat
# included in /etc/bewan/scripts/ip-down-lan
# environment variables are defined in the calling script

# Remove SNAT rules created on ip-up
ipdown_lan_nat() {
  [ ! -f /usr/bin/iptables ] && return 0

  local rule="$LAND/$LANID/ip/snat1"
  if [ -f "$rule" ]; then
    iptables -t nat -D `cat $rule`
    rm $rule
  fi
  rule="$LAND/$LANID/ip/snat2"
  if [ -f "$rule" ]; then
    iptables -t nat -D `cat $rule`
    rm $rule
  fi
}

ipdown_lan_nat
