#!/bin/sh
# /etc/bewan/ip-down-lan.d/K20lanarp
# called from /etc/bewan/scripts/ip-down-lan through sh
# No environement variable
# $LANID = lan interface index

restart_lanarp() {
	local ARG=restart
	base_call_initd 'lanarp'
}

restart_lanarp
