#!/bin/sh

# Called on ip-up event on a LAN interface
# $LANID= LAN connection index
restart_miniupnp() {
	[ ! -f /var/bewan/miniupnp.d/lan-interfaces ] && return 1
	local interfaces=`cat /var/bewan/miniupnp.d/lan-interfaces`

	# Restart if interface is in list
	local ok=0
	local ix
	for ix in `strip $interfaces`; do
		if [ "$ix" = "${LANID:-0}" ]; then
			ok=1
		fi
	done

	[ $ok = 0 ] && return 1

	local ARG=restart
	base_call_initd 'miniupnpd'
}

restart_miniupnp
