#!/bin/sh

# /etc/bewan/init.d/autoconfd $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

# Sanity check
check_autoconfd() {
  local enable="test -f $WAND/$WANID/ip6/autoconf"
  local active="base_exist_daemon $daemon"
  base_check_arg "$enable" "$active"
}

stop_autoconfd() {
  local pid=`cat $daemon_pid`
  base_kill_daemon $daemon "$pid"
  # Kill autoconfd now
  if [ "$pid" != '' ]; then
    base_call_initd 'inittab'
    # Release wan-up-down mutex
    base_exit_critical 'wan-up-down'
    # Wait autoconfd exit
    while kill -0 $pid; do
      sleep 1
    done
    # Take wan-up-down mutex
    base_enter_critical 'wan-up-down'
  fi
}

start_autoconfd() {
  local autoconf=
  if [ -f $WAND/$WANID/ip6/autoconf ]; then
    autoconf=$(cat $WAND/$WANID/ip6/autoconf)
  fi
  local cmd="autoconfd -i $WANID -n $ifname -p $daemon_pid $autoconf"
  base_add_daemon $daemon "$cmd"
}

main_autoconfd() {
  eval $PUSH_ARG

  local ifname=`cat $WAND/$WANID/ip6name`
  local daemon="autoconfd-$ifname"
  local daemon_pid="/var/run/$daemon.pid"

  check_autoconfd
  base_log "$INITD/autoconfd $ARG $ifname" debug

  case $ARG in
  stop)
    stop_autoconfd
    ;;
  start)
    start_autoconfd
    ;;
  restart)
    stop_autoconfd
    start_autoconfd
    ;;
  esac
}

main_autoconfd

