#!/bin/sh
# /etc/bewan/init.d/backup-config
# $1 = generated archive

which tar >/dev/null || exit 1

. /etc/bewan/lib/base

ARCHIVE=${1:-}
[ "$ARCHIVE" = '' ] && exit 1

base_enter_critical 'store.lock'
cd /nvram/bewan; tar cf $ARCHIVE * >/dev/null 2>/dev/null
base_exit_critical 'store.lock'
exit 0
