#!/bin/sh
# /etc/bewan/init.d/bcm63168_wan_port $1
# $1
# $2 or SWITCHID

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

if [ "$SWITCHID" = '' ]; then
  SWITCHID=${2:-}
fi

if [ "$SWITCHID" = '' ]; then
  base_log "bcm63168_wan_port : must a switch ID" error
  return
fi

local switch='Switch_'$SWITCHID
local name portlist portid ethidx
eval name=\${$switch'_Name':-}
eval portlist=\${$switch'_Port_List':-}
for portid in `strip $portlist`
do
  local port
  port=$switch'_Port_'$portid

  # Check if WANEthernetInterface is set
  eval ethidx=\${$port'_WANEthernetInterfaceIdx':-}
  if [ "$ethidx" != "" ]; then
    # Check if associated WAN interface is enabled
    local wanethitfname
    eval wanethitfname=\${'WANEthernetInterface_'$ethidx'_Ifname':-}
    if [ "$wanethitfname" != "" ]; then
      if [ ! -f /tmp/${wanethitfname}_already_wan_port ]; then
	touch /tmp/${wanethitfname}_already_wan_port
	bcm63168_set_wan_port $wanethitfname 1
      fi
    fi
  fi
done
