#!/bin/sh
# /etc/bewan/init.d/defroute6 $1
# $1 or $ARG = restart

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

check_defroute6() {
  [ "$ARG" != restart ] && ARG=nothing
  [ "$old_route" = "$new_route" ] && ARG=nothing
}

restart_defroute6() {
  if [ "$old_route" != '' ]; then
    WANID=$old_route
    base_call_initd 'wannet6'
  fi
  if [ "$new_route" != '' ]; then
    WANID=$new_route
    base_call_initd 'wannet6'
  fi
}

main_defroute6() {
  eval $PUSH_ARG

  local old_route new_route

  old_route=`cat $WAND/defroute6 2>/dev/null`
  new_route=${Layer3Forwarding_DefaultConnectionService6:-}

  check_defroute6
  base_log "$INITD/defroute6 $ARG" debug

  [ "$ARG" = restart ] && restart_defroute6
}

main_defroute6
