#!/bin/sh

# /etc/bewan/init.d/landhcp6 $1 $2
# $1 or $ARG = start stop restart
# $2 or $IFNAME = action for interface name

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

IFNAME=${IFNAME:-}
if [ "$IFNAME" = '' ]; then
  IFNAME=${2:-}
fi

# Sanity check
check_dhcp6s() {
  if ! which dhcp6s >/dev/null; then
    ARG=nothing
    return;
  fi
  local enable="test -f $daemon_conf"
  local active="base_exist_daemon $daemon"
  base_check_arg "$enable" "$active"
}

stop_dhcp6s() {
  local pid=`cat $daemon_pid`
  base_kill_daemon $daemon "$pid"
  # Kill dhcp6s now
  if [ "$pid" != '' ]; then
    base_call_initd 'inittab'
    # Wait dhcp6s exit
    while kill -0 $pid; do
      sleep 1
    done
  fi

  rm -f $daemon_conf
}

start_dhcp6s() {
  local cmd="dhcp6s -d -c $daemon_conf -P $daemon_pid -u $daemon_duid $ifname"
  base_add_daemon $daemon "$cmd"
}


main_dhcp6s() {
  eval $PUSH_ARG

  local ifname="$IFNAME"
  local daemon="dhcp6s-$ifname"
  local daemon_pid="/var/run/$daemon.pid"
  local daemon_conf="$DHCP6D/$ifname.conf"
  local daemon_duid="$DHCP6D/$ifname.duid"

  check_dhcp6s
  base_log "$INITD/dhcp6server $ARG $ifname" debug

  case $ARG in
  stop)
    stop_dhcp6s
    ;;
  start)
    start_dhcp6s
    ;;
  restart)
    stop_dhcp6s
    start_dhcp6s
    ;;
  esac
}

main_dhcp6s
