#!/bin/sh

# /etc/bewan/init.d/dhcp6client $1 $2
# $1 or $ARG = start stop restart
# $2 or $IFNAME = action for interface name

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

IFNAME=${IFNAME:-}
if [ "$IFNAME" = '' ]; then
  IFNAME=${2:-}
fi

# Sanity check
check_dhcp6c() {
  if ! which dhcp6c >/dev/null; then
    ARG=nothing
    return;
  fi
  local enable="test -f $daemon_conf"
  local active="base_exist_daemon $daemon"
  base_check_arg "$enable" "$active"
}

stop_dhcp6c() {
  local pid=`cat $daemon_pid`
  base_kill_daemon $daemon "$pid"
  # Kill dhcp6c now
  if [ "$pid" != '' ]; then
    base_call_initd 'inittab'
    # Release wan-up-down mutex
    base_exit_critical 'wan-up-down'
    # Wait dhcp6c exit
    while kill -0 $pid; do
      sleep 1
    done
    # Take wan-up-down mutex
    base_enter_critical 'wan-up-down'
  fi
}

start_dhcp6c() {
  local cmd="dhcp6c -d -c $daemon_conf -p $daemon_pid -u $daemon_duid $ifname"
  base_add_daemon $daemon "$cmd"
}


main_dhcp6c() {
  eval $PUSH_ARG

  local ifname="$IFNAME"
  local daemon="dhcp6c-$ifname"
  local daemon_pid="/var/run/$daemon.pid"
  local daemon_conf="$DHCP6CLIENTD/$ifname.conf"
  local daemon_duid="$DHCP6CLIENTD/$ifname.duid"

  check_dhcp6c
  base_log "$INITD/dhcp6client $ARG $ifname" debug

  case $ARG in
  stop)
    stop_dhcp6c
    ;;
  start)
    start_dhcp6c
    ;;
  restart)
    stop_dhcp6c
    start_dhcp6c
    ;;
  esac
}

main_dhcp6c
