#!/bin/sh
# /etc/bewan/init.d/dhcp $1 $2
# $1 or $ARG = start stop restart
# $2 or $IFNAME = stop or restart for interface name
# $2 or $IFNAME = all, action for all interfaces

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

IFNAME=${IFNAME:-}
if [ "$IFNAME" = '' ]; then
  IFNAME=${2:-}
fi

stop_dhcp() {
  # Shutdown daemons
  ARG=stop
  base_call_initd 'dnsmasq dhcrelay'
}

start_dhcp() {
  # Start daemons
  ARG=start
  base_call_initd 'dnsmasq dhcrelay'
}

main_dhcp() {
  eval $PUSH_ARG

  base_log "$INITD/dhcp $ARG $IFNAME" debug

  case $ARG in
  stop)
    stop_dhcp
    ;;
  start)
    start_dhcp
    ;;
  restart)
    stop_dhcp
    start_dhcp
    ;;
  esac
}

main_dhcp
