#!/bin/sh
# /etc/bewan/init.d/dhcrelay $1 $2
# $1 or $ARG = start stop restart
# $2 or $IFNAME = stop or restart for interface name
#FIXME $2 or $IFNAME = all, action for all interfaces

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

# debug set -x
IFNAME=${IFNAME:-}
if [ "$IFNAME" = "" ]; then
  IFNAME=${2:-}
fi

check_dhcrelay() {
  # sanity check
	if [ ! -f /bin/dhcp-fwd ]; then
		ARG=nothing
		return
	fi

	if [ "$IFNAME" = "" ]; then
		base_log "IFNAME is not set" "debug"
		ARG=nothing
		return
	fi

	local enable active
	enable="test -f $DHCRELAYD/$IFNAME"
	active="test -f $pidfile"
	base_check_arg "$enable" "$active"
} 

stop_dhcrelay() {
	local pid
  if [ "$IFNAME" = all ]; then
    # Destroy configuration for all interfaces
    [ "$ARG" = stop ] && rm -f $DHCRELAYD/*

    # all instances of dhcrelay need to be killed later
		pid="`cat /var/run/dhcp-fwd-*.pid 2>/dev/null`"
		base_kill_daemon "dhcp-fwd.*" "$pid"
  else
    # Destroy configuration for $IFNAME
    [ "$ARG" = stop ] && rm -f $DHCRELAYD/$IFNAME

    # dhcrelay instance need to be killed later
		pid="`cat $pidfile 2>/dev/null`"
		base_kill_daemon "$daemon" "$pid"
  fi
}

start_dhcrelay() {
	local ip server bind_on intf wanid lanid bind_on_ext
	local serial srv
	intf=$IFNAME
	
	server="`cat $DHCRELAYD/$intf 2>/dev/null`"
  bind_on="`cat $DHCRELAYD/$intf.bind 2>/dev/null`"
	if [ "$bind_on" = "" ]; then
		base_log "do nothing for $IFNAME (1)" debug
		return
	fi

	if [ -f "$DHCRELAYD/$intf.external" ]; then
		wanid=`cat $INTFD/$bind_on/wanid 2>/dev/null`
		ip=`cat $WAND/$wanid/ip/ipaddr 2>/dev/null`
		bind_on_ext=$bind_on
	else
		base_log "no explicit bind, do nothing for $IFNAME" debug
		return
#		lanid=`cat $INTFD/$bind_on/lanid 2>/dev/null`
#		ip=`cat $LAND/$lanid/ip/ipaddr 2>/dev/null`
#		def=`cat $WAND/defroute 2>/dev/null`
#		bind_on_ext=wan"$def"
#		if [ ! -f "$WAND/$def/ip/ipaddr" ]; then 
#			base_log "do nothing for $IFNAME (2)" debug
#			return
#		fi
	fi

	if [ "$ip" = "" ] || [ "$bind_on" = "" ]; then
		base_log "do nothing for $IFNAME (3)" debug
		return
	fi

	cat <<EOF >/var/bewan//dhcp-fwd.$intf
user    root
group   root
pidfile   $pidfile
ulimit core 0
ulimit stack  64K 
ulimit data 32K 
ulimit rss  200K
ulimit nproc  0
ulimit nofile 0
ulimit as 0
if $intf  true  false true
if $bind_on_ext false true false
name  $intf  ws-c
EOF
		first=
		for srv in $server; do
		first=$srv
cat <<EOF >>/var/bewan/dhcp-fwd.$intf
server  ip  $srv $bind_on
EOF
		done
serial=`pzinfo serial`
cat <<EOF >>/var/bewan/dhcp-fwd.$intf
# force GIADDR to this IP
ip $intf $ip
# replace OPTION 54 from WAN to LAN
option lan2 $first
# set 82.2 to SERIAL
remoteid lan2 $serial
EOF

	local cmd="/bin/dhcp-fwd -n -c /var/bewan/dhcp-fwd.$intf"
	base_add_daemon "$daemon" "$cmd"
}


main_dhcrelay() {
	eval $PUSH_ARG

	local daemon=dhcp-fwd.$IFNAME
	local pidfile="/var/run/dhcp-fwd-$IFNAME.pid"

	check_dhcrelay

	base_log "$INITD/dhcrelay $ARG $IFNAME" debug

	case $ARG in
	stop)
		stop_dhcrelay
		;;
	start)
		start_dhcrelay
		;;
	restart)
		stop_dhcrelay
		start_dhcrelay
		;;
	esac
}

main_dhcrelay

