#!/bin/sh
# /etc/bewan/init.d/domain $1
# $1 or $ARG = start stop restart

# script used when the parameter Domain is changed

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

check_domain() {
  [ "$ARG" = restart ] || ARG=nothing
}

restart_domain() {
  # Rebuild mdns service and /etc/hosts to reflect domain change
  base_call_initd 'mdns host'
  # Restart lan dhcp servers
  local LANID
  for LANID in `ls $LAND`; do
    if [ -f "$LAND/$LANID/dhcp/firstip" ]; then
      base_call_initd 'landhcp'
    fi
  done
}

main_domain() {
  eval $PUSH_ARG

  check_domain
  base_log "$INITD/domain $ARG" debug

  [ "$ARG" = restart ] && restart_domain
}

main_domain
