#!/bin/sh
# /etc/bewan/init.d/dsl $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

. /etc/bewan/lib/dsl

check_dsl() {
  if ! check_vendor_dsl ; then
    ARG=nothing
    return
  fi
  local enable="test x$WANDSLInterfaceConfig_Enable = x1"
  local active="test -d $DSLD"
  base_check_arg "$enable" "$active"
}

start_dsl() {
  mkdir -p $DSLD

  echo $modulation >/$DSLD/modulation
  start_vendor_dsl $modulation

  # Load ADSL statistics module
  modprobe adsl_stats_hal
  modprobe adsl_stats
}

stop_dsl() {
  stop_vendor_dsl
  rm -rf $DSLD
}

restart_dsl() {
  restart_vendor_dsl $modulation
  echo $modulation >/$DSLD/modulation
}

main_dsl() {
  eval $PUSH_ARG

  local modulation="$WANDSLInterfaceConfig_ModulationType"
  local datapump="$WANDSLInterfaceConfig_DataPumpVersion"

  check_dsl
  base_log "$INITD/dsl $ARG" debug

  case $ARG in
  stop)
    stop_dsl
    ;;
  start)
    start_dsl
    ;;
  restart)
    stop_dsl
    start_dsl
    ;;
  esac
}

main_dsl
