#!/bin/sh
# /etc/bewan/init.d/dslite $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

# Sanity check
check_dslite() {
  if [ ! -d $WAND/$WANID/ip -o ! -d $WAND/$WANID/ip6 ]; then
    ARG=nothing
    return
  fi
  # If ipcp is enabled, stop right now
  if [ -f $WAND/$WANID/ipcp ]; then
    ARG=nothing
    return
  fi

  eval en=\${'WANConnectionDevice_'$WANID'_WANIPConnection_Enable':-0}
  eval iptype=\${'WANConnectionDevice_'$WANID'_WANIPConnection_AddressingType':-None}

  local enable="test x$en = x1 -a x$iptype = xDSLite"
  local active="test -f $WAND/$WANID/ip6/tunnel"
  base_check_arg "$enable" "$active"
}

stop_dslite() {
  IFNAME=`cat $WAND/$WANID/ip6/tunnel`
  [ -z "${IFNAME:-}" ] && return

  base_call_scripts 'ip-down'
  ip -6 tunnel del $IFNAME
  rm -f $WAND/$WANID/ip6/tunnel
}

start_dslite() {
  eval localip6=\${'WANConnectionDevice_'$WANID'_WANIPConnection_DSLite_IP6Source'}
  eval remoteip6=\${'WANConnectionDevice_'$WANID'_WANIPConnection_DSLite_IP6Destination'}
  eval localip=\${'WANConnectionDevice_'$WANID'_WANIPConnection_DSLite_IP4Source'}
  eval remoteip=\${'WANConnectionDevice_'$WANID'_WANIPConnection_DSLite_IP4Destination'}

  # If nothing specified, use wan ip6 address
  [ -z "${localip6}" ] && localip6=`cat $WAND/$WANID/ip6/ipaddr`
  # No endpoint ...
  [ -z "${remoteip6}" ] && return
  [ -z "${localip}" ] && return
  [ -z "${remoteip}" ] && return

  IFNAME=dslite$WANID
  ip -6 tunnel add $IFNAME mode ipip6 local $localip6 remote $remoteip6 || return
  ip addr add $localip peer $remoteip dev $IFNAME || return
  ip link set $IFNAME up || return

  echo $IFNAME > $WAND/$WANID/ip6/tunnel
  echo $IFNAME > $WAND/$WANID/ip/ifname
  echo $IFNAME > $WAND/$WANID/ipname

  IPLOCAL=$localip
  IPADDR=$localip
  IPREMOTE=$remoteip
  SMASK=255.255.255.255
  ROUTERS=''
  DHCPSRV=''
  DOMAIN=''
  SERVERS=''

  base_call_scripts 'ip-up'
}

main_dslite() {
  eval $PUSH_ARG

  check_dslite
  base_log "$INITD/dslite $ARG $WANID" debug
  
  case $ARG in
  stop)
    stop_dslite
    ;;
  start)
    start_dslite
    ;;
  restart)
    stop_dslite
    start_dslite
   ;;
  esac
}

main_dslite
