#!/bin/sh
# /etc/bewan/init.d/easyp $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

check_easyp() {
  if [ ! -f /bin/pairingd ]; then
    ARG=nothing
    return
  fi
  local enable="test x$WLANConfig_EasyPairing = x1"
  local active='base_exist_daemon pairingd'
  base_check_arg "$enable" "$active"
}

start_easyp() {
  local opt=""
  local cmd

  ledmgmt=${WLANConfig_LedManagement:-1}
  if [ $ledmgmt -eq 0 ]; then
    opt="-l"
  else
    cmd="/bin/wifi_led_mgmt"
    base_add_daemon wifi_led_mgmt "$cmd"    
  fi

  # This is usefull if the software mode is overriden
  # by a hardware switch config
  if [ -f $WIFID/current_mode ]; then
    mode=`cat $WIFID/current_mode`
  else
    mode=${WLANConfig_Mode:-}
  fi
  if [ "$mode" != "" ]; then
    opt="$opt -m $mode"
  fi

  cmd="/bin/wifi_button"
  base_add_daemon wifi_button "$cmd"


  cmd="/bin/pairingd ${opt}"
  base_add_daemon pairingd "$cmd"
}

stop_easyp() {
  local pid

  pid=`pidof wifi_led_mgmt 2>/dev/null`
  if [ $? -eq 0 ]; then
    base_kill_daemon wifi_led_mgmt "$pid"
  fi

  pid=`pidof wifi_button 2>/dev/null`
  base_kill_daemon wifi_button "$pid"

  pid=`pidof pairingd 2>/dev/null`
  base_kill_daemon pairingd "$pid"
}

restart_easyp() {
  stop_easyp
  start_easyp
}

main_easyp() {
  eval $PUSH_ARG

  check_easyp
  base_log "$INITD/easyp $ARG" debug

  case $ARG in
  stop)
    stop_easyp
    ;;
  start)
    start_easyp
    ;;
  restart)
    restart_easyp
    ;;
  esac
}

main_easyp
