#!/bin/sh
# /etc/bewan/init.d/ethled $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

# Sanity check
check_ethled() {
  local en; eval en=\${'Services_EthernetLedMonitor_Enable':-0}

  base_log "This functionality is a work in progress, please don't use it" debug
  ARG=nothing
  return

  local enable="test x$en = x1"
  local active="test -f /var/bewan/ethled"
  base_check_arg "$enable" "$active"
}

stop_ethled() {  
  rmmod ethled
  rm -f /var/bewan/ethled
}

start_ethled() {
  local sw_idx=0
  local lan_idx=''
  local lan_phys=''

  # First, let's find our lan ethernet interfaces
  while [ "$sw_idx" -lt ${Switch_Count:-0} ]; do
    sw_idx=$(($sw_idx + 1))

    local port_idx=0
    local port_list; eval port_list=\${'Switch_'$sw_idx'_Port_List:-'}

    for port_idx in `strip $port_list`; do
      local port_en; eval port_en=\${'Switch_'$sw_idx'_Port_'$port_idx'_Enable:-0'}
      [ $port_en != 1 ] && continue

      eval lan_idx=\${'Switch_'$sw_idx'_Port_'$port_idx'_LANEthernetInterfaceIdx:-'}
      eval lan_idx=\${'Switch_'$sw_idx'_Port_'$port_idx'_LANEthernetInterfaceIdx:-'}
      [ -z "$lan_idx" ] && continue

      local lan_phy; eval lan_phy=\${'Switch_'$sw_idx'_Port_'$port_idx'_PhyId:-'}
      [ -z "$lan_phy" ] && continue

      if [ -z "$lan_phys" ]; then
        lan_phys="$lan_phy"
      else
        lan_phys="$lan_phys,$lan_phy"
      fi
    done
  done

  if [ -z "$lan_phys" ]; then
    return
  fi

  eth_name=eth0
  modprobe ethled eth_name=$eth_name phy_ids=$lan_phys
  touch /var/bewan/ethled
}

main_ethled() {
  eval $PUSH_ARG

  check_ethled
  base_log "$INITD/ethled $ARG" debug

  case $ARG in
  stop)
    stop_ethled
    ;;
  start)
    start_ethled
    ;;
  restart)
    stop_ethled
    start_ethled
    ;;
  esac
}

main_ethled
