#!/bin/sh
# /etc/bewan/init.d/firewall4 $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

IPPROTO=ipv4
base_call_initd 'firewall'
