#!/bin/sh

if [ "${ARG:-}" = '' ]; then
	. /etc/bewan/init.d/setparam
fi

add_dynamic_rules() {
	local filter_path=$NFDYND/filter
	local nat_path=$NFDYND/nat
	local mangle_path=$NFDYND/mangle

	local dyn_file=$NFDYND/iptables_dynamic
	> $dyn_file

	local file=
	local line=

	# Dynamics rules filter
	if [ -d $filter_path ]; then
		echo '*filter' >> $dyn_file
		for chain in input; do
			[ ! -d ${filter_path}/${chain} ] && continue
			local name=$(echo $chain |tr [a-z] [A-Z])
			local list="$(ls ${filter_path}/${chain}/* 2>/dev/null)"
			echo ':DYNAMIC'$name' - [0:0]' >> $dyn_file
			for file in $list; do
				cat $file |while read line; do
					echo "-A DYNAMIC$name $line" >> $dyn_file
				done
			done
		done
		echo "COMMIT" >> $dyn_file
	fi

	# Dynamics rules mangle
	if [ -d $mangle_path ]; then
		echo '*mangle' >> $dyn_file
		for chain in postrouting; do
			[ ! -d ${mangle_path}/${chain} ] && continue
			local name=$(echo $chain |tr [a-z] [A-Z])
			local list="$(ls ${mangle_path}/${chain}/* 2>/dev/null)"
			echo ':DYNAMIC'$name' - [0:0]' >> $dyn_file
			for file in $list; do
				cat $file |while read line; do
					echo "-A DYNAMIC$name $line" >> $dyn_file
				done
			done
		done
		echo "COMMIT" >> $dyn_file
	fi

	iptables-restore -n $dyn_file
}

add_dynamic_rules
