#!/bin/sh

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

change_usb() {
  if [ "${Services_GvtConfig_EnableUSB:-0}" = 1 ]; then
    modprobe ehci-hcd 2>/dev/null
    modprobe ohci-hcd 2>/dev/null
  else 
    rmmod ehci-hcd 2>/dev/null
    rmmod ohci-hcd 2>/dev/null
  fi
}

change_usb
