#!/bin/sh
# /etc/bewan/init.d/hpna $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

. /etc/bewan/lib/hpna

check_hpna() {
  if ! check_vendor_hpna ; then
    ARG=nothing
    return
  fi
  local enable="test x$HPNA_Enable = x1"
  local active="test -d $HPNAD"
  base_check_arg "$enable" "$active"
}

start_hpna() {
  mkdir -p $HPNAD
  start_vendor_hpna
}

stop_hpna() {
  stop_vendor_hpna
  rm -rf $HPNAD
}

restart_hpna() {
  restart_vendor_hpna
}

main_hpna() {
  eval $PUSH_ARG

  check_hpna
  base_log "$INITD/hpna $ARG" debug

  case $ARG in
  stop)
    stop_hpna
    ;;
  start)
    start_hpna
    ;;
  restart)
    stop_hpna
    start_hpna
    ;;
  esac
}

main_hpna
