#!/bin/sh
# from base_web
# /etc/bewan/init.d/http $1 $2
# $1 or $ARG = start stop restart
# $2 or $HTTP_ID = action for HttpServer_${id}
#

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi
HTTP_ID=${HTTP_ID:-}
if [ "$HTTP_ID" = '' ]; then
  HTTP_ID=${2:-}
fi

# sanity check

# Main
main_http() {
  eval $PUSH_ARG

  # short name for daemon entry in inittab
  local daemon="http-$HTTP_ID"
   
# call to load specific web server library functions
  . /etc/bewan/lib/web_server_functions

  check_http

  base_log "$INITD/http $ARG $HTTP_ID" debug

  case $ARG in
  stop)
    stop_http
    ;;
  start)
    start_http
    ;;
  restart)
    stop_http
    start_http
    ;;
  esac

  local STUNNEL_SERVICE="HttpServer_$HTTP_ID"
  base_call_initd 'stunnel'

  if [ "$ARG" = restart ]; then
    base_call_initd 'mdns'
  fi
}

# Work
main_http
