#!/bin/sh
# /etc/bewan/init.d/inittab
# build inittab file and reload it

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

rebuild_inittab() {
  local inittab='/var/bewan/inittab'
  local md5sum="`md5sum $inittab 2>/dev/null`"
  rm -f $inittab

  # Rebuild /etc/inittab:

  # syslog is the first to be launched
  [ -f /var/bewan/syslog ] && cp /var/bewan/syslog $inittab
  echo '/dev/null::respawn:/sbin/klogd -n' >>$inittab
  # Add configuration daemon
  if which configd >/dev/null; then
    echo '/dev/null::respawn:/sbin/configd' >>$inittab
  fi
  # Rebuild also BSP processes controlled through inittab
  [ -f /etc/inittab.default ] && cat </etc/inittab.default >>$inittab
  # Collect all daemons
  cat $ITABD/* >>$inittab 2>/dev/null

  # Reload inittab
  if [ "$md5sum" != "`md5sum $inittab`" ]; then
    kill -HUP 1
  fi
}

# Kill processes which pids are stored in $KILLS or KILLS9
kill_daemons() {
  local pids="`cat $KILLS 2>/dev/null`"
  if [ "$pids" != '' ]; then
    rm -f $KILLS
    kill $pids
  fi
  pids="`cat $KILLS9 2>/dev/null`"
  if [ "$pids" != '' ]; then
    rm -f $KILLS9
    kill -9 $pids
  fi
}

# Rebuild inittab under the inittab lock
base_enter_critical 'inittab.lock'
rebuild_inittab
base_exit_critical 'inittab.lock'

# Kill processes needed to be restarted or stopped
base_enter_critical 'kills.lock'
kill_daemons
base_exit_critical 'kills.lock'
