#!/bin/sh
#
# Pace V5471 42k Custom Series
# (c) Triple Oxygen - http://www.tripleoxygen.net
#

CONFIG_BACKUP="/nvram/gvt/config-backup.tar"
VOICE_BACKUP="/nvram/gvt/voice-backup.cli"

[[ ! -f "$CONFIG_BACKUP" ]] && /etc/bewan/scripts/backup-config-nvram "$CONFIG_BACKUP" 
[[ ! -f "$VOICE_BACKUP" ]] && /etc/bewan/scripts/backup-voice-profile "$VOICE_BACKUP"            
