#!/bin/sh
# /etc/bewan/init.d/internet $1
# $1 or $ARG = restart

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

check_internet() {
  [ "$ARG" != restart ] && ARG=nothing
  [ "$old_inet" = "$new_inet" ] && ARG=nothing
}

restart_internet() {
  local go ix

  echo $new_inet >$WAND/internet

  # Restart WAN interfaces in $old_inet but not in $new_inet
  for WANID in `strip $old_inet`; do
    go=1
    for ix in `strip $new_inet`; do
      [ "$WANID" = "$ix" ] && go=0
    done
    if [ "$go" = 1 ]; then
      IPPROTO=
      base_call_initd 'wannet'
    fi
  done
  # Restart WAN interfaces in NEW_INET
  for WANID in `strip $new_inet`; do
    IPPROTO=
    base_call_initd 'wannet'
  done
}

main_internet() {
  eval $PUSH_ARG

  local old_inet new_inet

  old_inet=`cat $WAND/internet 2>/dev/null`
  new_inet=${Layer3Forwarding_InternetConnectionService:-}

  check_internet
  base_log "$INITD/internet $ARG" debug

  [ "$ARG" = restart ] && restart_internet
}

main_internet
