#!/bin/sh

# /etc/bewan/init.d/ipv6 $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

restart_lanip6()
{
  local count=$1
  local index=0
  while [ $index -lt $count ]; do
    index=$(($index + 1))
    local LANID=$index
    local ARG=restart
    base_call_initd 'lanip6'
  done
}

restart_wannet6()
{
  local count=$1
  local index=0
  while [ $index -lt $count ]; do
    index=$(($index + 1))
    local WANID=$index
    local ARG=restart
    local ipv6cpen; eval ipv6cpen=\${'WANConnectionDevice_'$WANID'_WANPPPConnection_IPv6CPEnable':-0}
    unset DONT_TOUCH_PPP
    [ "$ipv6cpen" = 1 ] && DONT_TOUCH_PPP=0
    base_call_initd 'wannet6'
  done
}

# Sanity check
check_ipv6() {
  local enable="test x${Device_IPv6Enable:-0} = x1"
  local active="test -f $IP6ENABLE"
  base_check_arg "$enable" "$active"
}

stop_ipv6() {
  rm -f $IP6ENABLE
  local ARG=restart
  local IPPROTO=ipv6
  base_call_initd 'routes ip6tables fwrules'
  restart_wannet6 ${WANConnectionDevice_Count:-0} 
  restart_lanip6 ${LANDevice_Count:-0} 
}

start_ipv6() {
  touch $IP6ENABLE
  local ARG=restart
  local IPPROTO=ipv6
  restart_lanip6 ${LANDevice_Count:-0} 
  restart_wannet6 ${WANConnectionDevice_Count:-0} 
  base_call_initd 'fwrules ip6tables routes'
}

main_ipv6() {
  eval $PUSH_ARG

  check_ipv6
  base_log "$INITD/ipv6 $ARG" debug

  case $ARG in
  stop)
    stop_ipv6
    ;;
  start)
    start_ipv6
    ;;
  restart)
    stop_ipv6
    start_ipv6
    ;;
  esac
}

main_ipv6
