#!/bin/sh
# /etc/bewan/init.d/lan $1 $2
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

# Sanity check
check_lan() {
  if [ "$LANID" = '' ]; then
    ARG=nothing
    return
  fi
  local landev='LANDevice_'$LANID
  local en; eval en=\${$landev'_Enable':-}

  local enable="test x$en = x1"
  local active="test -d $LAND/$LANID"
  base_check_arg "$enable" "$active"
}

stop_lan() {
  # Remove IP/DHCP and physical interfaces
  ARG=stop
  ETHNAME=all
  base_call_initd 'passthrough lanacl lanip lanip6 lanif'

  # Remove LAN bridge
  local ifname=`cat $LAND/$LANID/ifname`
  ifconfig $ifname down
  brctl delbr $ifname

  # Remove ifname->lanid cross reference
  rm -rf $INTFD/$ifname
  # Remove lanid directory
  rm -rf $LAND/$LANID
}

start_lan() {
  local ifname stpen stp landev stp_interval

  # Create lanid directory
  eval ifname=\${'LANDevice_'$LANID'_Ifname':-lan$LANID}
  mkdir $LAND/$LANID
  echo $ifname >$LAND/$LANID/ifname

  # Create bridge
  landev='LANDevice_'$LANID
  eval stpen=\${$landev'_EnableSTP'}
  if [ "$stpen" = 1 ]; then
    stp='on'
  else
    stp='off'
  fi

  brctl addbr $ifname
  brctl stp $ifname $stp
  brctl setfd $ifname 5

  if [ "$stpen" = 1 ]; then
    eval stp_interval=\${$landev'_STPInterval'}
    brctl sethello $ifname $stp_interval
    brctl setageing $ifname 300
    brctl setfd $ifname 5
    brctl setmaxage $ifname 20
  else
    brctl setageing $ifname 10800
    brctl setfd $ifname 0
    brctl setmaxage $ifname 0
  fi

  # Add physical interfaces
  ARG=start
  ETHNAME=all
  base_call_initd 'lanif'

  # Add ifname->lanid cross reference
  mkdir $INTFD/$ifname
  echo $LANID >$INTFD/$ifname/lanid

  # Start interface
  ifconfig $ifname up

  # Set up IP interface
  ARG=start
  base_call_initd 'lanip lanip6 lanacl passthrough'
}

main_lan() {
  eval $PUSH_ARG

  check_lan
  base_log "$INITD/lan $ARG $LANID" debug

  case $ARG in
  stop)
    stop_lan
    ;;
  start)
    start_lan
    ;;
  restart)
    stop_lan
    start_lan
    ;;
  esac
}

if [ "$LANID" = 'all' ] && ( [ $ARG = start ] || [ $ARG = stop ] ); then

  # Start all lans
  count=${LANDevice_Count:-0}
  LANID=0; while [ $LANID -lt $count ]; do
    LANID=$(($LANID + 1))
    base_call_initd 'lan'
  done

  LANID='all'
  return
fi

main_lan
