#!/bin/sh
# /etc/bewan/init.d/lanacl $1 $2
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

. /etc/bewan/lib/wifi

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

check_lanacl() {
  local no_wifi=1 i en
  i=0; while [ $i -lt "$WLANInterface_Count" ]; do
    i=`expr $i + 1`
    eval en=\${'WLANInterface_'$i'_Enable'}
    [ "$en" = 1 ] && no_wifi=0 && break
  done
  [ "$no_wifi" = 1 ] && ARG=nothing
  [ "$WLANConfig_Enable" = 0 ] && ARG=nothing
}

start_lanacl() {
  start_vendor_lanacl
}

stop_lanacl() {
  stop_vendor_lanacl
}

restart_lanacl() {
  stop_lanacl
  start_lanacl
}

main_lanacl() {
  eval $PUSH_ARG

  check_lanacl
  base_log "$INITD/lanacl $ARG $LANID" debug

  case $ARG in
  stop)
    stop_lanacl
    ;;
  start)
    start_lanacl
    ;;
  restart)
    restart_lanacl
    ;;
  esac
}

if [ "$LANID" = 'all' ] && ( [ $ARG = start ] || [ $ARG = stop ] ); then
  # Start all WLAN Interfaces
  count=$LANDevice_Count
  LANID=0; while [ $LANID -lt $count ]; do
    LANID=$(($LANID + 1))
    base_call_initd 'lanacl'
  done

  LANID='all'
  return
fi

main_lanacl
