#!/bin/sh
# /etc/init.d/landhcp6 $1 $2
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

check_landhcp6() {
  if [ "$IFNAME" = "" ]; then
    ARG=nothing
    return
  fi
  local enable="test -d $LAND/$LANID/ip6"
  local active="test -d $LAND/$LANID/dhcp6"
  base_check_arg "$enable" "$active"
}

stop_relay_landhcp6() {
  base_log "stop_relay_landhcp6: TODO !!!"
}

start_relay_landhcp() {
  base_log "start_relay_landhcp6: TODO !!!"
}

stop_landhcp6() {

  # Stop DHCP daemons for $IFNAME
  ARG=stop
  base_call_initd 'dhcp6server'

  # Remove DHCP configuration
  rm -rf $LAND/$LANID/dhcp6
}

start_landhcp6() {

  mkdir $LAND/$LANID/dhcp6
  local landev='LANDevice_'$LANID

  local en; eval en=\${$landev'_HostConfig6_DHCPServer_Enable':-0}
  [ "$en" != 1 ] && return

#  local relay; eval relay=\${$landev'_HostConfig6_DHCPRelay_Enable':-0}
#  if [ "$relay" = "1" ]; then
#    start_relay_landhcp6
#    return
#  fi

  . /etc/bewan/lib/dhcp6server
  local ipaddr=`cat $LAND/$LANID/ip6/ipaddr 2>/dev/null`
  local lladdr=`cat $LAND/$LANID/ip6/lladdr 2>/dev/null`
  lladdr=${lladdr%%/*}
  local prefix=`cat $LAND/$LANID/ip6/prefix 2>/dev/null`
  local ifname=$IFNAME
  dhcp6server_config_lan $ifname

  # Start dhcp daemon
  ARG=start
  base_call_initd 'dhcp6server'
}

main_landhcp6() {
  eval $PUSH_ARG

  local IFNAME=`cat $LAND/$LANID/ifname 2>/dev/null`

  check_landhcp6
  base_log "$INITD/landhcp6 $ARG $LANID" debug

  case $ARG in
  stop)
    stop_landhcp6
    ;;
  start)
    start_landhcp6
    ;;
  restart)
    stop_landhcp6
    start_landhcp6
    ;;
  esac
}

main_landhcp6
