#!/bin/sh
# /etc/bewan/init.d/lanif $1 $2
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

. /etc/bewan/lib/lan

check_lanif() {
  if [ "$ifname" = '' ]; then
    ARG=nothing
    return
  fi
  local enable="test -f $LAND/$LANID/ifname"
  local active="test -f $LAND/$LANID/intfs"
  base_check_arg "$enable" "$active"
}

stop_lanif() {
  local intf
  for intf in $old_intfs; do
    remove_interface_from_lan_bridge $intf
  done
  rm -f $LAND/$LANID/intfs
}

rebuild_lan_interfaces()
{
  local new_intfs="`cat $LAND/$LANID/intfs 2>/dev/null`"
  local intf
  # Remove interfaces that are no more in lan bridge
  for intf in $old_intfs; do
    local found=0
    local itf
    for itf in $new_intfs; do
      [ "$intf" = "$itf" ] && found=1
    done
    [ $found = 1 ] && continue
    remove_interface_from_lan_bridge $intf
  done
  # Add all interfaces to lan bridge
  add_interface_to_lan_bridge all $LANID
}

start_lanif() {
  local landev iftype intfs ifs intf vid
  local count list en i j

  # Enumerate physical interfaces for this LAN device
  landev='LANDevice_'$LANID
  intfs=''
  for iftype in LANEthernetInterface LANUSBInterface WLANInterface; do
    eval count=\${$iftype'_Count':-0}
    i=0; while [ $i -lt $count ]; do
      i=$(($i + 1))
      eval intf=\${$iftype'_'$i'_Ifname'}
      [ "$intf" = '' ] && continue
      eval list=\${$landev'_'$iftype'_'$i'_VLANInterface_List':-}
      if [ "$list" = '' ]; then
        eval en=\${$landev'_'$iftype'_'$i'_Enable':-0}
        [ "$en" = 1 ] && intfs="$intfs $intf"
        continue
      fi
      eval list=\${$iftype'_'$i'_VLANInterface_List':-}
      for j in `strip $list`; do
        eval en=\${$landev'_'$iftype'_'$i'_VLANInterface_'$j'_Enable':-0}
        [ "$en" != 1 ] && continue
        eval vid=\${$iftype'_'$i'_VLANInterface_'$j'_VID'}
        [ "$vid" = '' ] && continue
        intfs="$intfs $intf.$vid"
      done
    done
  done
  echo $intfs >$LAND/$LANID/intfs
}

main_lanif() {
  eval $PUSH_ARG

  local ifname=`cat $LAND/$LANID/ifname 2>/dev/null`
  local old_intfs="`cat $LAND/$LANID/intfs 2>/dev/null`"

  check_lanif
  base_log "$INITD/lanif $ARG $LANID" debug

  case $ARG in
  stop)
    stop_lanif
    ;;
  start|restart)
    start_lanif
    rebuild_lan_interfaces
    ;;
  esac
}

if [ "$LANID" = 'all' ] && [ $ARG = restart ]; then

  # Restart all lanif (used by vlaneth)
  count=${LANDevice_Count:-0}
  LANID=0; while [ $LANID -lt $count ]; do
    LANID=$(($LANID + 1))
    base_call_initd 'lanif'
  done

  LANID='all'
  return
fi

main_lanif
