#!/bin/sh
# /etc/bewan/init.d/lanlease $1 $2
# $1 or $ARG = restart
# $2 or $LANID = action for lanid

# Script called when a parameter of ClientTable is changed
# branch to /etc/init.d/landhcp with DONT_REMOVE_LEASES = 1

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

[ "$ARG" != restart ] && exit 0

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

base_log "$INITD/lanlease $ARG $LANID" debug

DONT_REMOVE_LEASES=1
base_call_initd 'landhcp'
