#!/bin/sh
# /etc/bewan/init.d/lenneighbor $1
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi
LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

set_arp_cache_locktime() {
	local arp_cache_locktime; eval arp_cache_locktime=\${'LANDevice_'$LANID'_Neighbor_ARPCacheLocktime':-0}

	if [ ${arp_cache_locktime} -ne 0 ] && [ -f /proc/sys/net/ipv4/neigh/$IFNAME/locktime ]; then
		echo ${arp_cache_locktime}  > /proc/sys/net/ipv4/neigh/$IFNAME/locktime
	fi
}

set_arp_cache_timeout() {
	local arp_cache_timeout; eval arp_cache_timeout=\${'LANDevice_'$LANID'_Neighbor_ARPCacheTimeout':-0}

	if [ ${arp_cache_timeout} -ne 0 ] && [ -f /proc/sys/net/ipv4/neigh/$IFNAME/gc_stale_time ]; then
		echo ${arp_cache_timeout}  > /proc/sys/net/ipv4/neigh/$IFNAME/gc_stale_time
	fi
}

main_lanneighbor() {
	eval $PUSH_ARG
	local IFNAME=`cat $LAND/$LANID/ifname 2>/dev/null`

	if [ "$IFNAME" = "" ]; then
		return
	fi

 	base_log "$INITD/lanneighbor $ARG $IFNAME" debug

	#This is to change ARPCache timeout
	set_arp_cache_timeout
	#This is to change ARPCache locktime
	set_arp_cache_locktime
}

main_lanneighbor
