#!/bin/sh
# /etc/bewan/init.d/lanndp $1 $2
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

# Sanity check
check_lanndp() {
  if ! which lanndpd >/dev/null; then
    ARG=nothing
    return
  fi
  local en; eval en=\${'LANDevice_'$LANID'_HostNDPKeepAlive':-0}

  local enable="test x$en = x1 -a -f $LAND/$LANID/ip6/ipaddr"
  local active="base_exist_daemon $daemon"
  base_check_arg "$enable" "$active"
}

stop_lanndp() {
  # Kill lanndpd daemon
  local pid=`cat $daemon_pid`
  base_kill_daemon $daemon "$pid"
#  # Disable arp config
#  echo 0 >/proc/sys/net/ipv4/conf/$ifname/arp_ignore
#  echo 0 >/proc/sys/net/ipv4/conf/$ifname/arp_accept
#  if [ -f /proc/sys/net/ipv4/conf/$ifname/arp_noisy ]; then
#    echo 0 >/proc/sys/net/ipv4/conf/$ifname/arp_noisy
#  fi
}

start_lanndp() {
#  # answer for arp requests only from the same subnet
#  echo 2 >/proc/sys/net/ipv4/conf/$ifname/arp_ignore
#  # Accept gratuitous arp requests
#  echo 1 >/proc/sys/net/ipv4/conf/$ifname/arp_accept
#  # Allow to record in arp cache gratuitous arp requests not for us
#  if [ -f /proc/sys/net/ipv4/conf/$ifname/arp_noisy ]; then
#    echo 1 >/proc/sys/net/ipv4/conf/$ifname/arp_noisy
#  fi
  # Launch lanndpd daemon
  local cmd="/usr/bin/lanndpd -i $ifname -p $daemon_pid"
  base_add_daemon $daemon "$cmd"
}

restart_lanndp() {
  local pid=`cat $daemon_pid`
  kill -HUP $pid
}

main_lanndp() {
  eval $PUSH_ARG

  local ifname=`cat $LAND/$LANID/ifname 2>/dev/null`
  local daemon="lanndp-$ifname"
  local daemon_pid="/var/run/$daemon.pid"

  check_lanndp
  base_log "$INITD/lanndp $ARG $LANID" debug

  case $ARG in
  stop)
    stop_lanndp
    ;;
  start)
    start_lanndp
    ;;
  restart)
    restart_lanndp
    ;;
  esac
}

if [ "$LANID" = 'all' ] && ( [ $ARG = start ] || [ $ARG = stop ] ); then

  # Start all lanndp daemons
  count=${LANDevice_Count:-0}
  LANID=0; while [ $LANID -lt $count ]; do
    LANID=$(($LANID + 1))
    base_call_initd 'lanndp'
  done

  LANID='all'
  return
fi

main_lanndp
