#!/bin/sh
# sh /etc/init.d/lanphy $1 $2
# $1 = start / stop /restart
# $2 = action for lanid

# Always called through sh
# Not included in other scripts

# Get configuration parameters
. /etc/bewan/init.d/setparam

ARG=${1:-nothing}
LANID=${2:-0}

base_log "$INITD/lanphy $ARG $LANID" debug

[ $ARG != restart ] && return

do_lanphy_v1() {
  # This implementation reset phy of all ports
  # without coping with LANID (difficult with vlans)

  # Enumerate physical ethernet interfaces and reset phy of each port
  local count=${LANEthernetInterface_Count:-0}
  local ETHID=0
  while [ $ETHID -lt $count ]; do
    ETHID=`expr $ETHID + 1`
    local ports; eval ports=\${'LANEthernetInterface_'$ETHID'_Port_List':-}
    local PORTID
    for PORTID in `strip $ports`; do
      base_call_initd 'phy'
    done
  done
}

# TODO: what about vlan interfaces ???
do_lanphy_v2() {
  # Loops on all ethernet interfaces included in this LAN device object
  local ethcount; eval ethcount=\${'LANDevice_'$LANID'_LANEthernetInterface_Count':-0}
  local ethid=0
  while [ $ethid -lt $ethcount ]; do
    ethid=$(($ethid + 1))
    local en; eval en=\${'LANDevice_'$LANID'_LANEthernetInterface_'$ethid'_Enable':-0}
    # Skip ethernet inteface not included in the LAN devce object
    [ $en = 0 ] && continue

    # Loops on all switch objects
    local SWITCHID=0
    while [ $SWITCHID -lt $swcount ]; do
      SWITCHID=$(($SWITCHID + 1))
      local ports; eval ports=\${'Switch_'$SWITCHID'_Port_List':-}
      # Loops on all ports of the current switch object
      local PORTID
      for PORTID in $(strip $ports); do
        local lanethid; eval lanethid=\${'Switch_'$SWITCHID'_Port_'$PORTID'_LANEthernetInterfaceIdx':-0}
        # Skip port not asociated to the ethernet interface object
        [ $lanethid != $ethid ] && continue
        base_call_initd 'phy'
      done
    done
  done
}

swcount=${Switch_Count:-0}

# Put all ethernet phys in power down
ARG=stop
if [ $swcount = 0 ]; then
  do_lanphy_v1
else
  do_lanphy_v2
fi

# Restart all ethernet phys auto negotiation
ARG=start
if [ $swcount = 0 ]; then
  do_lanphy_v1
else
  do_lanphy_v2
fi
