#!/bin/sh
# /etc/bewan/init.d/lanlease $1 $2
# $1 or $ARG = restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

[ "$ARG" != restart ] && exit 0

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

base_log "$INITD/lanrange $ARG $LANID" debug

base_call_initd 'landhcp'
base_call_initd 'lanarp'

