#!/bin/sh
# /etc/bewan/init.d/lanthrough $1 $2
# $1 or $ARG = restart
# $2 or $LANID = action for lanid

# Script called when parameter UseAllocatedWAN is changed
# branch to /etc/init.d/bewan/landhcp with DO_PASSTHROUGH = 1

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

[ "$ARG" != restart ] && exit 0

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

base_log "$INITD/lanthrough $ARG $LANID" debug

DO_PASSTHROUGH=1
base_call_initd 'landhcp'
