#!/bin/sh
# /etc/bewan/init.d/manage-store $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

# check
check_storage()
{
  local enable="test x$Storage_Enable = x1"
  base_check_arg "$enable" ""
}

# stop
stop_storage() {
	### for each partition : to do umount
	storage_list=`echo "status 1;cd _Storage_Item;get List" | cli -q`
	for item in `echo $storage_list | tr "," " "`
	do 
		status_mount=`echo "status 1;cd _Storage_Item_${item}_Status;get State" | cli -q`
		if [ $status_mount = "ConnectedMounted" ]
		then
			cli -q <<EOF
			cd _Storage_Item_${item}_Status
			sset State "forceumount"
EOF
		fi
	done

}

# start
start_storage() {
	### for each partition : to do umount
	storage_list=`echo "status 1;cd _Storage_Item;get List" | cli -q`
	for item in `echo $storage_list | tr "," " "`
	do 
		status_mount=`echo "status 1;cd _Storage_Item_${item}_Status;get State" | cli -q`
		if [ $status_mount != "ConnectedMounted" ]
		then
			cli -q <<EOF
			cd _Storage_Item_${item}_Status
			sset State "mount"
EOF
		fi
	done
}

main_storage() {
  eval $PUSH_ARG
  check_storage

  case $ARG in
  stop)
    stop_storage
    ;;
  start)
    start_storage
    ;;
  restart)
    stop_storage
    start_storage
    ;;
  esac
}

# work
main_storage