#!/bin/sh
# /etc/bewan/init.d/manage-store $1 $2
# $1 or $ARG = start stop restart
# $2 : item storage index

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

ITEM=${ITEM:-}
if [ "$ITEM" = '' ]; then
  ITEM=${2:-}
fi


# get the mode of the partition
# returns 0 : read only
# returns 1 : read and write
# returns 2 : the device is not mounted
get_mode()
{
	local device=`echo "status 1;cd _Storage_Item_${ITEM}_Status;get Device" | cli -q`
	local result=`cat /proc/mounts | grep "$device"`
	if [ "$result" = "" ]
	then
		return 2
	fi
	result=`echo $result | grep "ro,"`
	if [ "$result" = "" ]
	then
		return 1
	else
		return 0
	fi
}

# check if the value of Storage_Item_{i}_Share_Writable has changed
# and modify the value of ARG according this state
# ARG : nothing -> restart : if Storage_Item_{i}_Share_Enable = 1 and if Storage_Item_{i}_Share_Writable has changed
check_writable()
{
	local storage_item='Storage_Item_'${ITEM}
	local mode; eval mode=\${$storage_item'_Share_Writable'}
	if [ $ARG = "nothing" ]
	then
		get_mode
		local result=$?
		if [ $result -eq 2 ]
		then
			ARG=nothing
		elif [ $result -ne $mode ]
		then
			ARG=restart
		fi
	fi
}


# check if the value of Storage_Item_{i}_Share_Enable has changed
# start : state : disable -> enable
# nothing : no changement
# stop : state : enable -> disable
check_mountpoint()
{
	local active=0
	if [ "$ITEM" = "0" ]
	then
		ARG=nothing
		exit 0
	fi
	local enable_storage=${Storage_Enable:-0}
	if [ "$enable_storage" = "0" ]
	then
		ARG=nothing
		exit 0
	fi
	local part=`echo "status 1;cd _Storage_Item_${ITEM}_Status;get Device" | cli -q`
	local storage_item='Storage_Item_'${ITEM}
	local enable_str; eval enable_str=\${$storage_item'_Share_Enable'}
	local enable="test x$enable_str = x1"
	cat /proc/mounts | grep "$part" 2>&1 >/dev/null
	if [ "$?" = "0" ]
	then
		active=1
	fi
	base_check_arg "$enable" "test x$active = x1"
}

# stop
stop_mountpoint() {
	### for the ITEM partition : to do umount
	cli -q <<EOF
	cd _Storage_Item_${ITEM}_Status
	sset State "forceumount"
EOF
}

# start
start_mountpoint() {
	cli -q <<EOF
	cd _Storage_Item_${ITEM}_Status
	sset State "mount"
EOF
}

main_mountpoint() {
	eval $PUSH_ARG
	check_mountpoint
	check_writable
	base_log "/etc/bewan/init.d/mountpoint $ARG $ITEM" debug
	case $ARG in
	stop)
		stop_mountpoint
		;;
	start)
		start_mountpoint
		;;
	restart)
		stop_mountpoint
		start_mountpoint
		;;
	esac
}

# work
main_mountpoint

