#!/bin/sh
# /etc/bewan/init.d/passthrough $1 $2
# $1 or $ARG = start stop restart
# $2 or $LANID = action for lanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

LANID=${LANID:-}
if [ "$LANID" = '' ]; then
  LANID=${2:-}
fi

check_passthrough() {
  if [ ! -d "$LAND/$LANID" ]; then
    ARG=nothing
    return
  fi
  local enable="test x$new_wanid != x"
  local active="test x$old_wanid != x"
  base_check_arg "$enable" "$active"
}

stop_passthrough() {
  # Destroy LAN-WAN bridge cross reference links
  rm -f $BRIDGED/$lanifname
  rm -f $BRIDGED/wan$old_wanid
}

start_passthrough() {
  # Setup bridge cross reference links
  echo $new_wanid >$BRIDGED/$lanifname
  echo $LANID >$BRIDGED/wan$new_wanid
}

restart_wan_passthrough() {
  local doipt=0
  if [ "$old_wanid" != '' ] && [ "$old_wanid" != "$new_wanid" ]; then
    [ "$ARG" != "start" ] && doipt=1
    ARG=restart
    WANID=$old_wanid
    base_call_initd 'wan'
  fi
  if [ "$new_wanid" != "" ]; then
    [ "$ARG" != "start" ] && doipt=1
    ARG=restart
    WANID=$new_wanid
    base_call_initd 'wan'
  fi
  if [ "$doipt" = 1 ]; then
    ARG=restart
    base_call_initd 'iptables ip6tables'
  fi
}

main_passthrough() {
  eval $PUSH_ARG

  local old_wanid new_wanid

  eval lanifname=\${'LANDevice_'$LANID'_Ifname':-lan$LANID}
  old_wanid=`cat $BRIDGED/$lanifname 2>/dev/null`
  eval new_wanid=\${'LANDevice_'$LANID'_HostConfig_AssociatedConnection'}

  check_passthrough
  base_log "$INITD/passthrough $ARG $LANID" debug

  case $ARG in
  stop)
    stop_passthrough
    restart_wan_passthrough
    ;;
  start)
    start_passthrough
    restart_wan_passthrough
    ;;
  restart)
    stop_passthrough
    start_passthrough
    restart_wan_passthrough
    ;;
  esac
}

main_passthrough
