#!/bin/sh
# /etc/bewan/init.d/restore-config
# $1 = file that contains the configuration to restore

which tar >/dev/null || exit 1

. /etc/bewan/lib/base

TMPDIR=/var/tmp/nvram

# Untar the archive given in argument
if [ "${1:-}" != '' ]; then
  mkdir -p $TMPDIR
  cd $TMPDIR; tar xf $1
  if [ $? != 0 ]; then
    # Wrong archive
    base_log 'Invalid Archive in restored Configuration' debug
    # Give up
    rm -rf $TMPDIR
    exit 1
  fi
  cd /var/tmp
fi

# Check for configuration files to install
if [ ! -f $TMPDIR/router.diff ]; then
    # Wrong archive
    base_log "Invalid restored Configuration" debug
    # Give up
    rm -rf $TMPDIR
    exit 1
fi

# --------------------------------------------------
# Configuration system version 2 with configd daemon
# --------------------------------------------------
if which configd >/dev/null; then

  # Copy the TR069 notify list if exists
  if [ -f $TMPDIR/notifylist ]; then
    base_enter_critical 'save.lock'
    cp $TMPDIR/notifylist /var/bewan/tmp/notify.save
    base_exit_critical 'save.lock'
  fi
  # Apply the imported diff
  echo "applydiff $TMPDIR/router.diff" | cli -q

# ---------------------------------------------
# Configuration system version 1 with configlib
# ---------------------------------------------
else
  # Copy the TR069 notify list if exists
  base_enter_critical 'save.lock'
  cp $TMPDIR/notifylist /var/bewan/tmp/notify.save
  base_exit_critical 'save.lock'
  # Rebuild a configuration file with restored router.diff
  confpatch /var/bewan/factory.conf $TMPDIR/router.diff /var/tmp/router.conf
  # switch current configuration to new one
  base_enter_critical 'config.lck'
  mv /var/tmp/router.conf /var/bewan/router.conf
  base_exit_critical 'config.lck'
  # Commit the new configuration to system and save it in flash
  echo "fbuild; fcommit 1" | cli -s
fi

# NEED A REBOOT
base_log "REBOOT IS NEEDED" debug

rm -rf $TMPDIR
exit 0
