#!/bin/sh
# /etc/bewan/init.d/routes $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

IPPROTO=${IPPROTO:-}

[ -d /proc/sys/net/ipv4 ] && [ -f /etc/bewan/lib/ipv4_routing_functions ] && . /etc/bewan/lib/ipv4_routing_functions
[ -d /proc/sys/net/ipv6 ] && [ -f /etc/bewan/lib/ipv6_routing_functions ] && . /etc/bewan/lib/ipv6_routing_functions

check_routes() {
  [ "$IPPROTO" = 'ipv4' ]  && check_routes_ipv4
  [ "$IPPROTO" = 'ipv6' ]  && check_routes_ipv6
}

stop_routes() {
  [ "$IPPROTO" = 'ipv4' ] && stop_routes_ipv4
  [ "$IPPROTO" = 'ipv6' ] && stop_routes_ipv6
}

init_routes() {
  [ "$IPPROTO" = 'ipv4' ] && init_routes_ipv4
  [ "$IPPROTO" = 'ipv6' ] && init_routes_ipv6
}

start_routes() {
  [ "$IPPROTO" = 'ipv4' ] && start_routes_ipv4
  [ "$IPPROTO" = 'ipv6' ] && start_routes_ipv6

  # Brings up static routes
  local l3f='Layer3Forwarding_Forwarding_'
  local num=200
  local list=${Layer3Forwarding_Forwarding_List:-}
  for i in `strip $list`; do
    num=$(($num + 1))
    local en; eval en=\${$l3f$i'_Enable'}
    [ "$en" != 1 ] && continue
    local proto; eval proto=\${$l3f$i'_Protocol'}

    case "$proto" in
    'IPv4'|'')
      [ "$IPPROTO" = 'ipv4' ] && add_route_ipv4 $i
    ;;
    'IPv6')
      [ "$IPPROTO" = 'ipv6' ] && add_route_ipv6 $i
    ;;
    'IPv4+IPv6')
      [ "$IPPROTO" = 'ipv4' ] && add_route_ipv4 $i
      [ "$IPPROTO" = 'ipv6' ] && add_route_ipv6 $i
    ;;
    esac
  done
}

main_routes() {
  eval $PUSH_ARG
  local IPPROTO=$1

  check_routes
  base_log "$INITD/routes $IPPROTO $ARG" debug

  case $ARG in
  stop)
    stop_routes
    ;;
  start)
    init_routes
    start_routes
    ;;
  restart)
    stop_routes
    start_routes
    ;;
  esac
}

case "$IPPROTO" in
  ipv4)
    [ ${IPV4_ROUTING_LIB:-0} = 1 ] && main_routes ipv4
  ;;
  ipv6)
    [ ${IPV6_ROUTING_LIB:-0} = 1 ] && main_routes ipv6
  ;;
  '')
    [ ${IPV4_ROUTING_LIB:-0} = 1 ] && main_routes ipv4
    [ ${IPV6_ROUTING_LIB:-0} = 1 ] && main_routes ipv6
  ;;
esac
