#!/bin/sh
# /etc/bewan/init.d/rtsp_conntrack $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

check_rtsp_conntrack() {
  local enable="test x$Conntrack_RTSPConntrack_Enable = x1"
  local active="test x`lsmod | grep nf_conntrack_rtsp | wc -l` != x0"
  base_check_arg "$enable" "$active"
}

start_rtsp_conntrack() {
  local args="ports=$port"
  if [ "$pausetimeout" != "0" ]; then
    args="$args refresh_pause_time=$pausetimeout"
  fi
  /sbin/modprobe nf_conntrack_rtsp_hal
  /sbin/modprobe nf_conntrack_rtsp $args
  /sbin/modprobe nf_nat_rtsp
}

stop_rtsp_conntrack() {
  /sbin/modprobe -r nf_nat_rtsp  
  /sbin/modprobe -r nf_conntrack_rtsp
  /sbin/modprobe -r nf_conntrack_rtsp_hal
}

main_rtsp_conntrack() {
  eval $PUSH_ARG

  local port="$Conntrack_RTSPConntrack_Port"
  local pausetimeout="${Conntrack_RTSPConntrack_PauseTimeout:-0}"

  check_rtsp_conntrack
  base_log "$INITD/rtsp_conntrack $ARG" debug

  case $ARG in
  stop)
    stop_rtsp_conntrack
    ;;
  start)
    start_rtsp_conntrack
    ;;
  restart)
    stop_rtsp_conntrack
    start_rtsp_conntrack
    ;;
  esac
}

main_rtsp_conntrack
