#!/bin/sh
#saveTR069_debug $1
#$1 is the name of the directory to create in the USB flash disk and 
#in whichone the debug file will be copied.

USBDISK=`ls /var/mnt/`

if [ "$USBDISK" = "" ]
then
	echo "Error no USBDISK detected on the box. TR069 debug files not saved."
	exit 1;	
fi	

if [ "$1" = "" ]
then
	echo "Error The directory name is empty. TR069 debug files not saved."
	exit 1;
fi

for partition in $USBDISK
do
	if [ -d "/var/mnt/${partition}" ]
	then
		read_mount=$(cat /proc/mounts)
		for line in $read_mount
		do
			result=$(expr match "$line" "/var/mnt/$partition")
			if [ $result -ne 0 ]
			then
				mkdir -p "/var/mnt/${partition}/${1}"
				result=$?
				if [ $result -eq 0 ]
				then
					echo "Write TR069 logs in /var/mnt/${partition}"
					DIR="/var/mnt/${partition}/${1}"
					cp /var/tmp/resp* $DIR
					cp /var/tmp/post* $DIR
					rm -f /var/tmp/resp* 
					rm -f /var/tmp/post* 
					exit 0
				else
					exit 0
				fi
			fi
		done
		exit 0
	fi
done

exit 1;
