#!/bin/sh
# /etc/bewan/init.d/save-config

. /etc/bewan/lib/base

# Acquire the lock that controls access to the file save.conf
base_enter_critical 'save.lock'

# Copy the current configuration file to save.conf
base_enter_critical 'config.lck'
cp /var/bewan/router.conf /var/bewan/tmp/save.conf
base_exit_critical 'config.lck'

# Release the lock
base_exit_critical 'save.lock'
# Spawn the background process to store this config in flash
start-stop-daemon -S -b -x /etc/bewan/init.d/store-config
