#!/bin/sh
# /etc/bewan/init.d/store-config2

# Store configuration files to nvram, version 2 (using configd daemon)

. /etc/bewan/lib/base
. /etc/bewan/lib/config

# save.diff is the configuration diff file to save in permanent storage
# notify.save is the tr069 notification list to save in permanent storage

# Acquire the lock that controls exclusive access to nvram
base_enter_critical 'store.lock'
# Acquire the lock that controls access to the files save.diff and notify.save
# tr069 takes also this lock when it creates notify.save
base_enter_critical 'save.lock'
# If none of the files save.diff nor notify.save exit
if [ ! -f /var/bewan/tmp/save.diff ] && [ ! -f /var/bewan/tmp/notify.save ]; then
  # Release the locks and exit
  base_exit_critical 'save.lock'
  base_exit_critical 'store.lock'
  exit 0
fi

base_log "Storing configuration to NVRAM" debug
# Rename save.diff
[ -f /var/bewan/tmp/save.diff ] && mv /var/bewan/tmp/save.diff /var/bewan/tmp/store.diff
# Rename notify.save (tr069 permanent notify list to save)
[ -f /var/bewan/tmp/notify.save ] && mv /var/bewan/tmp/notify.save /var/bewan/tmp/notify.store
# And release the save lock
base_exit_critical 'save.lock'

# Allow temporary writes to /nvram
config_mtd_write
[ ! -d /nvram/bewan ] && mkdir /nvram/bewan
# Copy the diff file
[ -f /var/bewan/tmp/store.diff ] && mv /var/bewan/tmp/store.diff /nvram/bewan/router.diff
# Create the magic diff file
(wc -c </nvram/bewan/router.diff) >/nvram/bewan/router.magic
# Copy tr069 permanent notify list to flash
[ -f /var/bewan/tmp/notify.store ] && mv /var/bewan/tmp/notify.store /nvram/bewan/notifylist
# Copy config filestsytem to flash
config_mtd_store
# And release the store lock
base_exit_critical 'store.lock'
base_log "Store Done" debug
