#!/bin/sh
# /etc/init.d/switch_vlan $1 $2
# $1 or $ARG = start stop restart
# $2 or $SWITCHID = interface index

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

if [ "${SWITCHID:-}" = '' ]; then
  SWITCHID=${2:-}
fi

# Sanity check
check_switch_vlan_8021q() {
  if ! which $utility >/dev/null; then
    ARG=nothing
    return
  fi
  local enable="test x$enable = x1"
  local active="test -f $SWITCHD/$SWITCHID/vlan8021q"
  base_check_arg "$enable" "$active"
}

stop_switch_vlan_8021q() {
  $utility $switchname $accesstype disable
  rm $SWITCHD/$SWITCHID/vlan8021q
}

start_switch_vlan_8021q() {
  mkdir -p $SWITCHD/$SWITCHID
  touch $SWITCHD/$SWITCHID/vlan8021q
  local index=1

  $utility $switchname $accesstype enable

  for vlan in `strip $vlanlist`
  do
    eval en=\${$switch'_VLAN_'$vlan'_Enable':-0}
    [ "$en" != "1" ] && continue
    eval vid=\${$switch'_VLAN_'$vlan'_VID':-}
    [ "$vid" = "" ] && continue
    eval fid=\${$switch'_VLAN_'$vlan'_FID':-0}
    eval member=\${$switch'_VLAN_'$vlan'_MemberPorts':-}
    [ "$member" = "" ] && continue
    eval tagged=\${$switch'_VLAN_'$vlan'_TaggedPorts':-}

    local memberportmap=0
    for pt in `strip $member`
    do
      local portid
      eval portid=\${$switch'_Port_'$pt'_PortId':-}
      if [ "$portid" != "" ]; then
        memberportmap=$(( ${memberportmap} | 1 << ${portid} ))
      fi
    done

    local taggedportmap=0
    for pt in `strip $tagged`
    do
      local portid
      eval portid=\${$switch'_Port_'$pt'_PortId':-}
      if [ "$portid" != "" ]; then
        taggedportmap=$(( ${taggedportmap} | 1 << ${portid} ))
      fi
    done

    $utility "$switchname" "$accesstype" new "$ports" "$vid" "$fid" "$memberportmap" "$taggedportmap" "$index"
    index=$(( $index + 1 ))
  done

  $utility $switchname $accesstype post_new
}

main_switch_vlan_8021q() {
  eval $PUSH_ARG

  local switch='Switch_'$SWITCHID
  local switchname accesstype
  eval switchname=\${$switch'_Name':-}
  eval accesstype=\${$switch'_AccessType':-}
  local utility=$switchname'_vlanctl'
  local portlist
  eval portlist=\${$switch'_Port_List':-}
  local port
  local ports=""

  # Build a list of ports of this switch
  for port in `strip $portlist`
  do
    eval portid=\${$switch'_Port_'$port'_PortId':-}
    [ "$portid" = "" ] && continue
    if [ "$ports" = "" ]; then
      ports=$portid
    else
      ports="$ports,$portid"
    fi
  done 


  local enable
  local vlanlist vlan
  local en

  # Test if at least one VLAN is enabled
  enable=0
  eval vlanlist=\${$switch'_VLAN_List':-}
  for vlan in `strip $vlanlist`
  do
    eval en=\${$switch'_VLAN_'$vlan'_Enable':-0}
    if [ "$en" = "1" ]; then
      enable=1
    fi
  done

  check_switch_vlan_8021q
  base_log "$INITD/switch_vlan_8021q $ARG $SWITCHID" debug

  case $ARG in
  stop)
    stop_switch_vlan_8021q
    ;;
  start)
    start_switch_vlan_8021q
    ;;
  restart)
    stop_switch_vlan_8021q
    start_switch_vlan_8021q
    ;;
  esac
}

if [ "$SWITCHID" = 'all' ]; then
  TMPSWITCHID=$SWITCHID
  SWITCHID=0
  local count=${Switch_Count:-0}
  while [ $SWITCHID -lt $count ]
  do
    SWITCHID=$(($SWITCHID + 1))
    base_call_initd 'switch_vlan_8021q'
  done
  SWITCHID=$TMPSWITCHID
  return
fi

main_switch_vlan_8021q

