#!/bin/sh
# /etc/init.d/switch_vlan $1 $2
# $1 or $ARG = start stop restart
# $2 or $SWITCHID = interface index

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

if [ "${SWITCHID:-}" = '' ]; then
  SWITCHID=${2:-}
fi

# Sanity check
check_switch_vlan_portbased() {
  if ! which $utility >/dev/null; then
    ARG=nothing
    return
  fi
  local enable="test x$enable = x1"
  local active="test -f $SWITCHD/$SWITCHID/portbasedvlan"
  base_check_arg "$enable" "$active"
}

stop_switch_vlan_portbased() {
  $utility $switchname $accesstype del
  rm $SWITCHD/$SWITCHID/portbasedvlan
}

start_switch_vlan_portbased() {
  mkdir -p $SWITCHD/$SWITCHID
  touch $SWITCHD/$SWITCHID/portbasedvlan

  for vlan in `strip $vlanlist`
  do
    local first=1
    local portmap=""
    eval en=\${$switch'_PortBasedVLAN_'$vlan'_Enable':-0}
    eval ports=\${$switch'_PortBasedVLAN_'$vlan'_Ports':-}
    if [ "$en" = "1" ] && [ "$ports" != "" ]; then
      for pt in `strip $ports`
      do
        local portid
        eval portid=\${$switch'_Port_'$pt'_PortId':-}
        if [ "$portid" != "" ]; then
          if [ "$first" = "1" ]; then
            portmap="$portid"
            first=0
          else
            portmap="$portmap,$portid"
          fi
        fi
      done
      $utility $switchname $accesstype add $portmap
    fi
  done
}

main_switch_vlan_portbased() {
  eval $PUSH_ARG

  local switch='Switch_'$SWITCHID
  local switchname accesstype
  eval switchname=\${$switch'_Name':-}
  eval accesstype=\${$switch'_AccessType':-}
  local utility=$switchname'_portbasedvlanctl'

  local enable
  local vlanlist vlan
  local en ports

  # Test if at least one VLAN is enabled
  enable=0
  eval vlanlist=\${$switch'_PortBasedVLAN_List':-}
  for vlan in `strip $vlanlist`
  do
    eval en=\${$switch'_PortBasedVLAN_'$vlan'_Enable':-0}
    eval ports=\${$switch'_PortBasedVLAN_'$vlan'_Ports':-}
    if [ "$en" = "1" ] && [ "$ports" != "" ]; then
      enable=1
    fi
  done

  check_switch_vlan_portbased
  base_log "$INITD/switch_vlan_portbased $ARG $SWITCHID" debug

  case $ARG in
  stop)
    stop_switch_vlan_portbased
    ;;
  start)
    start_switch_vlan_portbased
    ;;
  restart)
    stop_switch_vlan_portbased
    start_switch_vlan_portbased
    ;;
  esac
}

if [ "$SWITCHID" = 'all' ]; then
  TMPSWITCHID=$SWITCHID
  SWITCHID=0
  local count=${Switch_Count:-0}
  while [ $SWITCHID -lt $count ]
  do
    SWITCHID=$(($SWITCHID + 1))
    base_call_initd 'switch_vlan_portbased'
  done
  SWITCHID=$TMPSWITCHID
  return
fi

main_switch_vlan_portbased
