#!/bin/sh
# /etc/bewan/init.d/tr069 $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

# check
check_tr069()
{
  if [ ! -e /bin/tr069 ]; then
    ARG=nothing
    return
  fi
  local enable="test x$Services_TR069_Enable = x1"
  local active="base_exist_daemon $daemon"
  base_check_arg "$enable" "$active"
}

# stop
stop_tr069() {
  # CPE daemon
  local pid="`cat $daemon_pid`"
  base_kill_daemon $daemon "$pid"
  rm -f $pwdfile
}

# start
start_tr069() {
  rm -f $pwdfile
  # CPE daemon
  local cmd="/bin/tr069 2>&1 | /usr/bin/logger -t TR-069 -p warning"
  if [ "$Services_TR069_SrvLogin" != '' ]; then
    local pwd=$( base_get_password "$Services_TR069_SrvPassword" )
    echo "$Services_TR069_SrvLogin:$pwd" >$pwdfile
  elif [ -e '/lib/libwebauth.so' ]; then
    # Create an invalid pasword file for security reasons (line without :)
    echo "invalid entry" >$pwdfile
  else
    # Create a special password file 
    echo "NO_CHECK_USER" > $pwdfile
  fi
  base_add_daemon $daemon "$cmd" /dev/console
}

main_tr069() {
  eval $PUSH_ARG

  local daemon=tr069
  local daemon_pid=/var/run/$daemon.pid
  local dir=/var/bewan/tr069
  local pwdfile=/var/bewan/tr069/.htpasswd

  mkdir -p $dir
  echo "Idle" > $dir/SessionStatus

  check_tr069
  base_log "$INITD/tr069 $ARG" debug

  case $ARG in
  stop)
    stop_tr069
    ;;
  start)
    start_tr069
    ;;
  restart)
    stop_tr069
    start_tr069
    ;;
  esac
}

# work
main_tr069
