#!/bin/sh
# /etc/bewan/init.d/tr069 $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = "" ]; then
	. /etc/bewan/init.d/setparam
fi
	
update_passwd() {
	local pwdfile=/var/bewan/tr069/.htpasswd
	rm -f $pwdfile
	if [ "$Services_TR069_SrvLogin" != '' ]; then
		local pwd=$( base_get_password "$Services_TR069_SrvPassword" )
		echo "$Services_TR069_SrvLogin:$pwd" >$pwdfile
	elif [ -e '/lib/libwebauth.so' ]; then
		# Create an invalid pasword file for security reasons (line without :)
		echo "invalid entry" >$pwdfile
	else
		# Create a special password file 
		echo "NO_CHECK_USER" > $pwdfile
	fi
}


update_passwd
