#!/bin/sh
# /etc/bewan/init.d/tr111_interfaces

# LAN DHCP server send an 125 DHCP option if the LAN interface is TR-111 capable
# The WAN prerouting table includes a jump to WT111 table if WT111 is enabled and WAN interface is TR069

# To be sure we commit the changes correctly
# we restart landhcp for all lans
# we restart firewall for all wans

if [ "${ARG:-}" = "" ]; then
	. /etc/bewan/init.d/setparam
fi

# Restart landhcp script for all lans
tr111_restart_landhcp() {

	local ARG=restart
	local count=${LANDevice_Count:-0}
	local LANID=0; while [ $LANID -lt $count ]; do
		LANID=$(($LANID + 1))
		base_call_initd 'landhcp'
	done
}

# Restart firewall script for all wans
tr111_restart_firewall() {

	local ARG=restart
	local count=${WANConnectionDevice_Count:-0}
	local WANID=0; while [ $WANID -lt $count ]; do
		WANID=$(($WANID + 1))
		base_call_initd 'firewall'
	done
}

main_tr111_interfaces() {

	base_log "$INITD/tr111_interfaces" $ARG debug

	case $ARG in
	start | stop | restart)
		tr111_restart_landhcp
		tr111_restart_firewall
		;;
	esac
}

# main
main_tr111_interfaces
