#!/bin/sh
# Potentially modify old config parameters when the firmware is upgraded
# This file is included at the beginning of the main rc

# CLI - use silent mode (sset, smk ...) to modify parameters silently and permanently, 
# without starting onchange script.

RELOAD_CONFIG=0

# Build SIP UserAgent string
build_ua() {
  
  local ver="`cat /etc/bewan/release`"
  local ua="Pace $Device_Product_ProductClass $ver"
  local i
  for i in `strip $VoiceProfile_List`; do
    local uai; eval uai=\${'VoiceProfile_'$i'_SIP_UserAgent':-}

    [ "$ua" = "$uai" ] && continue

    base_log "Set VoiceProfile $i UA=$ua" debug
    echo "cd _VoiceProfile_${i}_SIP;sset UserAgent '$ua'" | cli -q
    [ "$RELOAD_CONFIG" = 0 ] && RELOAD_CONFIG=1
  done
}

# Configure Hotspot address
config_hotspot() {
  local ip=$Services_GvtHotspot_Address_1_IP
  if [ "$VPNInterface_1_GRE_IP4Destination" != "$ip" ]; then
    echo "cd _VPNInterface_1_GRE; sset IP4Destination $ip; fcommit" | cli -q
    RELOAD_CONFIG=1
  fi
}

base_log "$INITD/update-config" debug

build_ua
config_hotspot

# Configuration is modified
if [ "$RELOAD_CONFIG" = 1 ]; then
  # Commit changes
  echo 'fcommit' | cli -q
  # Reload configuration parameters
  PARAM_LOADED=0
  base_load_param
fi

base_log "update-config done" debug
