#!/bin/sh
# /etc/bewan/init.d/user $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = '' ]; then
	. /etc/bewan/init.d/setparam
fi

generate_users() {
	local idx
	for idx in `strip $User_List`; do
		local enable; eval enable=\${'User_'$idx'_Enable'}
		[ "$enable" != 1 ] && continue
		local username; eval username=\${'User_'$idx'_Username'}
		[ "$username" = '' ] && continue
		local password; eval password=\${'User_'$idx'_Password'}
		[ "$password" = '' ] && password='EMPTY_PASSWORD'
		password=$( base_get_password $password )
		local services; eval services=\${'User_'$idx'_Services'}
		[ "$services" = '' ] && continue

		local srv
		for srv in `strip $services`; do
			local service="`echo $srv | cut -d_ -f1`"
			local en; eval en=\${$service'_Enable':-0}
			[ "$en" != 1 ] && continue
			local group="`echo $srv | cut -d_ -f2-`"
			local fct=$service"_generate_user"
			local r="$( $fct $username $password $group )"
			[ "$r" != '' ] && echo "$r"
		done
	done
	return 0
}

main_user() {
	eval $PUSH_ARG

	base_log "$INITD/users $ARG" debug

	local userd=/etc/bewan/user.d
	# include all /etc/bewan/user.d functions: unix, samba, nas, web...
	local service
	for service in $userd/*; do
		local shortname=`basename $service`
		base_log "import $shortname" debug
		. $service
	done 

	if [ "$ARG" = "start" ] || [ "$ARG" = "restart" ]; then
		generate_users
	fi
}

main_user
