#!/bin/sh
# /etc/bewan/init.d/voip $1
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = '' ]; then
	. /etc/bewan/init.d/setparam
fi

##################################################
# Sanity check
##################################################
check_voip() {
	if ! which voip >/dev/null; then
		ARG=nothing
		return
	fi
	local enable="test x$Voice_Enable = x1"
	local active='base_exist_daemon voip'
	base_check_arg "$enable" "$active"
}

###################################################
# Start voip 
##################################################
voip_start () {
	local cmd="/usr/bin/voip"
	local pid=`cat /var/run/voip.pid 2>/dev/null`
	local start=1
	if [ "$pid" != "" ]; then
		kill -0 $pid
		start=$?
		if [ $start -eq 1 ]; then
			#no process ongoing, do cleanup
			rm -f /var/run/voip.pid 2>/dev/null
			rm -f /var/run/voip.lock 2>/dev/null
		else
			base_log "voip is already running (pid=$pid), cannot start the service" debug
		fi
	fi
	if [ $start -eq 1 ]; then
		base_add_daemon "voip" "$cmd" 
	fi
}

##################################################
# Stop voip 
##################################################
voip_stop () {
	local pid=`cat /var/run/voip.pid 2>/dev/null`
	if [ "$pid" != "" ]; then
		if [ -f /var/run/voip.lock ]; then
			base_log "voip lock, cancel stop request" debug
			return
		fi
		base_kill_daemon "voip" "$pid"
		if [ "$TOP_ARG" = restart ]; then
			# Trigger initd to kill the voip immediately if we are restarting
			base_call_initd 'inittab'
			# Wait for voip exit
			local try=0
			while [[ $try -lt 10 ]] ; do
				kill -0 $pid
				if [ $? -eq 1 ]; then
					base_log "voip is not running anymore, exit" debug
					break
				fi
				try=`expr $try + 1`
				base_log "voip is still running, wait for 1s... (try=$try) " debug
				sleep 1
			done
			#kill -9 if still alive
			kill -0 $pid
			if [ $? -eq 0 ]; then
				base_log "voip is still running => hard KILL" debug
				base_kill9_daemon "voip" "$pid"
			fi
		fi
	fi
}

##################################################
# Main
##################################################
voip_main() {
	eval $PUSH_ARG

	check_voip

	base_log "$INITD/voip $ARG" debug

	case $ARG in

	start)
		voip_start ;;

	stop)
		voip_stop ;;

	init)
		voip_start ;;

	restart)
		voip_stop
		voip_start
		;;
	esac      
}

voip_main
