#!/bin/sh
# /etc/bewan/init.d/wanbr $1 $2
# $1 or $ARG = start stop restart

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

main_wanautoconf() {
  # If no autoconf, do nothing
  if [ ${Services_WANAutoConfig_Enable:-0} = 0 ]; then
    return
  fi

  # Here, we need to restart physical links in order to catch up adsl-up or waneth-up events

  # Restart DSL link
  local ARG=restart
  base_call_initd 'dsl'

  # Restart WAN Ethernet phys
  local SWITCHID=0
  local PORTID
  while [ $SWITCHID -lt ${Switch_Count:-0} ]
  do
    SWITCHID=$(($SWITCHID + 1))
    local switch='Switch_'$SWITCHID
    local portlist
    eval portlist=\${$switch'_Port_List':-}
    for PORTID in `strip $portlist`
    do
      local port
      port=$switch'_Port_'$PORTID
      # Check if WANEthernetInterface affects this switch
      eval ethidx=\${$port'_WANEthernetInterfaceIdx':-}
      if [ "$ethidx" != "" ]; then
          base_call_initd 'phy'
      fi
    done 
  done
}

main_wanautoconf
