#!/bin/sh
# /etc/bewan/init.d/wanbr $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

. /etc/bewan/lib/wan

# Sanity check
check_wanbr() {
  if [ ! -d "$WAND/$WANID/ip" ]; then
    ARG=nothing
    return
  fi
  local enable="test -f $WAND/$WANID/wan_bridged -a -f $LAND/$lanid/ifname"
  local active="test -f $WAND/$WANID/bridge"
  base_check_arg "$enable" "$active"
}

stop_wanbr() {

  local intfs intf

  # Remove WAN interface from LAN bridge
  local count=`cat $WAND/$WANID/count`
  if [ $count -gt 1 ]; then
    intfs=`ls $WAND/$WANID/intfs`
  else
    intfs=`cat $WAND/$WANID/ifname`
  fi

  local lanbr=`cat $WAND/$WANID/bridge`
  for intf in $intfs; do
    brctl delif $lanbr $intf
  done
  rm -f $WAND/$WANID/bridge
}

start_wanbr() {

  local intfs intf

  # Set up Full-Bridge
  local count=`cat $WAND/$WANID/count`
  if [ $count -gt 1 ]; then
    intfs=`ls $WAND/$WANID/intfs`
  else
    intfs=`cat $WAND/$WANID/ifname`
  fi

  local lanbr=`cat $LAND/$lanid/ifname`
  for intf in $intfs; do
    ifconfig $intf 0.0.0.0
    brctl addif $lanbr $intf
  done

  echo $lanbr >$WAND/$WANID/ip/ifname
  echo $lanbr >$WAND/$WANID/bridge
}

main_wanbr() {
  eval $PUSH_ARG

  local lanid=`cat $BRIDGED/wan$WANID 2>/dev/null`

  check_wanbr
  base_log "$INITD/wanbr $ARG $WANID" debug

  case $ARG in
  stop)
    stop_wanbr
    ;;
  start)
    start_wanbr
    ;;
  restart)
    stop_wanbr
    start_wanbr
    ;;
  esac
}

main_wanbr
