#!/bin/sh
# /etc/bewan/init.d/wandmz $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

base_log "$INITD/wandmz $ARG $WANID" debug

# Script used to restart WAN when DMZ has changed

NOPFW=1
NOIPT=0
base_call_initd 'firewall'
