#!/bin/sh
# /etc/bewan/init.d/wanif $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

#!/bin/sh
if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

base_log "$INITD/wanif $ARG $WANID" debug

# Script used to restart WAN when MAC address is changed

NOFWL=1
NOPFW=1
NOIPT=1
base_call_initd 'wan'
