#!/bin/sh
# /etc/bewan/init.d/wanl2filter $1 $2
# $1 or $ARG = restart
# $2 or $WANID = action for wanid

#!/bin/sh
if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

# Layer 2 Filter
restart_wanl2filter() {
  local ifname=`cat $WAND/$WANID/ifname 2>/dev/null`
  local l2f; eval l2f=\${'WANConnectionDevice_'$WANID'_L2Filter'}
  case "$l2f" in
  None) ethmux filter $ifname none 2>/dev/null;;
  PPPoE) ethmux filter $ifname pppoe 2>/dev/null;;
  IPARP) ethmux filter $ifname iparp 2>/dev/null;;
  IPv6) ethmux filter $ifname ipv6 2>/dev/null;;
  *) ;;
  esac
}

[ "$ARG" != restart ] && exit 0
[ ! -f $WAND/$WANID/ifname ] && exit 0
which ethmux >/dev/null || exit 0

base_log "$INITD/wanl2filter $ARG $WANID" debug

restart_wanl2filter
