#!/bin/sh
# /etc/bewan/init.d/wannat $1 $2
# $1 or $ARG = start stop restart
# $2 or $WANID = action for wanid

# Script used when NAT configuration has changed
# apply change without restart wan completely

# See code in /etc/bewan/scripts/ip-up
# See code in /etc/bewan/scripts/update_nat

if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

restart_wannat() {
  local snat dnat enat tmo
  # Remove current parameters
  rm -f $WAND/$WANID/ip/enablenat
  rm -f $WAND/$WANID/ip/nattimeout

  # Remove current SNAT rule
  snat=`cat $WAND/$WANID/ip/snat 2>/dev/null`
  [ "$snat" != '' ] && iptables -t nat -D $snat
  rm -f $WAND/$WANID/ip/snat

  # Remove current DNAT rule
  dnat=`cat $WAND/$WANID/ip/dnat 2>/dev/null`
  [ "$dnat" != '' ] && iptables -t nat -D $dnat
  rm -f $WAND/$WANID/ip/dnat

  # Reload new parameters
  eval enat=\${'WANConnectionDevice_'$WANID'_NATEnable'}
  if [ "$enat" = 1 ] && [ ! -f $WAND/$WANID/bridge ]; then
    # UDP NAT persistance timer
    eval tmo=\${'WANConnectionDevice_'$WANID'_NATTimeout'}
    [ "$tmo" != '' ] && echo $tmo >$WAND/$WANID/ip/nattimeout
    # new nat enable flag
    touch $WAND/$WANID/ip/enablenat
  fi

  # Recreate rules if necessary
  local ifname=`cat $WAND/$WANID/ip/ifname 2>/dev/null`
  local ipaddr=`cat $WAND/$WANID/ip/ipaddr 2>/dev/null`
  if [ -f $WAND/$WANID/ip/enablenat ] && [ "$ifname" != '' ] && [ "$ipaddr" != '' ]; then

    # SNAT rule
    tmo=`cat $WAND/$WANID/ip/nattimeout 2>/dev/null`
    [ "$tmo" != '' ] && tmo="--timeout $tmo"
    snat="POSTROUTING -o $ifname -j SNAT --to $ipaddr $tmo"
    echo $snat >$WAND/$WANID/ip/snat
    iptables -t nat -A $snat

    # DNAT rule
    dnat="PREROUTING -d $ipaddr -j PREROUTING$WANID"
    echo $dnat >$WAND/$WANID/ip/dnat
    iptables -t nat -A $dnat
  fi
}

[ "$ARG" != restart ] && exit 0
[ ! -e /usr/bin/iptables ] && exit 0
[ ! -f $WAND/$WANID/ifname ] && exit 0

# Do the stuff under update-nat lock
base_enter_critical 'update-nat'
base_log "$INITD/wannat $ARG $WANID" debug
restart_wannat
base_exit_critical 'update-nat'
