#!/bin/sh
# /etc/bewan/init.d/wanstp $1 $2
# $1 or $ARG = restart
# $2 or $WANID = action for wanid

#!/bin/sh
if [ "${ARG:-}" = '' ]; then
  . /etc/bewan/init.d/setparam
fi

WANID=${WANID:-}
if [ "$WANID" = '' ]; then
  WANID=${2:-}
fi

restart_wanstp() {
  local ifname=`cat $WAND/$WANID/ifname 2>/dev/null`
  local stpen; eval stpen=\${'WANConnectionDevice_'$WANID'_EnableSTP'}
  local stp=off; [ "$stpen" = 1 ] && stp=on
  brctl stp $ifname $stp
}

[ "$ARG" != restart ] && exit 0
[ ! -f $WAND/$WANID/ifname ] && exit 0

base_log "$INITD/wanstp $ARG $WANID" debug

restart_wanstp
