#!/bin/sh
# /etc/bewan/init.d/web_iad $1
# $1 or $ARG = start stop restart
# 

if [ "${ARG:-}" = '' ]; then
	. /etc/bewan/init.d/setparam
fi

# sanity check
check_web_iad() {
	local enable="test x$Services_IADConfigurator_Enable = x1"
	local active="test -f $http_server"
	base_check_arg "$enable" "$active"
}

# stop
stop_web_iad() {

	# Retrieve the current index of the associated HTTP server
	HTTP_ID=`cat $http_server 2>/dev/null`
	rm -rf $dir

	# Stop the associated HTTP server
	ARG=stop
	base_call_initd 'http'
}

# start
start_web_iad() {

	# Save the current index of the associated HTTP server
	mkdir -p $dir
	HTTP_ID="$Services_IADConfigurator_HttpServer"
	HTTP_SESSION_MAXLIMIT="$Services_IADConfigurator_MaxSessionLimit"
	echo $HTTP_ID >$http_server
	echo $HTTP_SESSION_MAXLIMIT >$http_session_maxlimit

	# Start the associated HTTP server
	ARG=start
	base_call_initd 'http'
}

# main
main_web_iad() {
	eval $PUSH_ARG

	local dir='/var/bewan/webiad.d'
	local http_server="$dir/http_server"	
	local http_session_maxlimit="$dir/http_session_maxlimit"
	check_web_iad
	base_log "$INITD/web_iad $ARG" debug

	case $ARG in
	stop)
		stop_web_iad
		;;
	start)
		start_web_iad
		;;
	restart)
		stop_web_iad
		start_web_iad
		;;
	esac
}

# work
main_web_iad
