#!/bin/sh
# /etc/bewan/init.d/wifi $1 $2
# $1 or $ARG = start stop restart
# $2 or $ETHID = WIFI interface index

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi


ETHID=${ETHID:-}
if [ "$ETHID" = '' ]; then
  ETHID=${2:-0}
fi

check_wifi() {
  local wlanconfigen=${WLANConfig_Enable:-0}
  local en; eval en=\${'WLANInterface_'$ETHID'_Enable':-0}
  local enable="test x$en = x1 -a x$wlanconfigen = x1"
  local active="test -d $WIFID/$ifname"
  base_check_arg "$enable" "$active"
}


if [ -f /etc/bewan/lib/wifissid ]; then
  . /etc/bewan/lib/wifissid
else
  . /etc/bewan/lib/wifi
fi

restart_wifi() {
    restart_vendor_wifi
}

main_wifissid() {
  eval $PUSH_ARG

  local ifname; eval ifname=\${'WLANInterface_'$ETHID'_Ifname'}

  check_wifi

  base_log "$INITD/wifissid $ARG $ETHID" debug

  case $ARG in
  restart)
    restart_wifi
    ;;
  esac
}

main_wifissid
