#!/bin/sh
# /etc/bewan/init.d/wifi $1 $2
# $1 or $ARG = start stop restart
# $2 or $ETHID = WIFI interface index

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

. /etc/bewan/lib/wifi

ETHID=${ETHID:-}
if [ "$ETHID" = '' ]; then
  ETHID=${2:-all}
fi

check_wifi() {
  if ! check_vendor_wifi; then
    ARG=nothing
    return
  fi

  local wlanconfigen=${WLANConfig_Enable:-0}
  local en; eval en=\${'WLANInterface_'$ETHID'_Enable':-0}
  local enable="test x$en = x1 -a x$wlanconfigen = x1"
  local active="test -d $WIFID/$ifname"
  base_check_arg "$enable" "$active"
}

start_wifi() {
  mkdir -p $WIFID/$ifname
  start_vendor_wifi
}

stop_wifi() {
  stop_vendor_wifi
  rm -rf $WIFID/$ifname
}

restart_wifi() {
  restart_vendor_wifi
}

main_wifi() {
  eval $PUSH_ARG

  local ifname; eval ifname=\${'WLANInterface_'$ETHID'_Ifname'}

  check_wifi
  base_log "$INITD/wifi $ARG $ETHID" debug

  case $ARG in
  stop)
    stop_wifi
    ;;
  start)
    start_wifi
    ;;
  restart)
    restart_wifi
    ;;
  esac
}

if [ "$ETHID" = 'all' ]; then

  # Start all WLAN Interfaces
  ETHID=0; while [ $ETHID -lt $WLANInterface_Count ]; do
    ETHID=$(($ETHID + 1))
    base_call_initd 'wifi'
  done

  ETHID='all'
  return
fi

main_wifi
