#!/bin/sh
# /etc/bewan/init.d/wpspincode $1 $2
# $1 or $ARG = restart
# $2 or $ETHID = WIFI interface index

if [ "${ARG:-}" = "" ]; then
  . /etc/bewan/init.d/setparam
fi

. /etc/bewan/lib/wifi

ETHID=${ETHID:-}
if [ "$ETHID" = '' ]; then
  ETHID=${2:-0}
fi

check_wpspincode() {
  if [ "$ARG" != restart ]; then
    ARG=nothing
    return
  fi

  local no_wifi=1 i en
  i=0; while [ $i -lt "$WLANInterface_Count" ]; do
    i=`expr $i + 1`
    eval en=\${'WLANInterface_'$i'_Enable'}
    [ "$en" = 1 ] && no_wifi=0 && break
  done
  [ "$no_wifi" = 1 ] && ARG=nothing
  [ "$WLANConfig_Enable" = 0 ] && ARG=nothing
}

restart_wpspincode() {
  restart_vendor_wpspincode
}

main_wpspincode() {
  eval $PUSH_ARG

  check_wpspincode
  base_log "$INITD/wpspincode $ARG $ETHID" debug

  case $ARG in
  restart)
    restart_wpspincode
    ;;
  esac
}

main_wpspincode
