#!/bin/sh
# /etc/bewan/scripts/association-up
# called when Wifi station gets associated with an AP

. /etc/bewan/scripts/globals
. /etc/bewan/lib/base

base_log "$SCRIPTD/association-up" debug

# Enter association-up-down critical section
base_enter_critical "association-up-down"
base_log "$SCRIPTD/association-up entered" debug

for script in `find /etc/bewan/association-up.d -follow -type f 2>/dev/null | sort`; do
  base_log "$script up $@" debug
  $script up $@
done
[ ! -f $RCRUNNING ] && base_call_initd 'inittab'

# Exit association-up-down critical section
base_log "$SCRIPTD/association-up exited" debug
base_exit_critical "association-up-down"
