#!/bin/sh
# /etc/bewan/scripts/association-down
# called when station is disassociated from its Access Point

. /etc/bewan/scripts/globals
. /etc/bewan/lib/base

base_log "$SCRIPTD/association-down" debug

# Enter association-up-down critical section
base_enter_critical "association-up-down"
base_log "$SCRIPTD/association-down entered" debug

for script in `find /etc/bewan/association-down.d -follow -type f 2>/dev/null | sort`; do
  base_log "$script down $@" debug
  $script down $@
done
[ ! -f $RCRUNNING ] && base_call_initd 'inittab'

# Exit adsl-up-down critical section
base_log "$SCRIPTD/association-down exited" debug
base_exit_critical "association-up-down"
