#!/bin/sh
# script call by the dnsmasq DHCP server when a lease change

# environnment variables:
# DNSMASQ_INTERFACE, lan interface
# ACTION, add, old, del
# MAC, host MAC address
# IP, new host IP address
# HOST, hostname

DNSMASQ_INTERFACE="${DNSMASQ_INTERFACE:-}"
[ "$DNSMASQ_INTERFACE" = '' ] && exit 0

ACTION="${1:-}" MAC="${2:-}" IP="${3:-}" HOST="${4:-}"

. /etc/bewan/init.d/setparam

base_log "$SCRIPTD/dhcpd-call $DNSMASQ_INTERFACE $ACTION $MAC $IP $HOST" debug

# Includes the scripts located in /etc/bewan/dhcp.d
for script in `find /etc/bewan/dhcp.d -follow -type f | sort`; do
  . $script
done
