#!/bin/sh

# Temporarily disable pktflow processing
# TODO: incompatibility with dhclient
# TODO: incompatibility with Bewan pppd

export LD_LIBRARY_PATH=/lib/public:/lib/private:/lib/gpl:/lib
fc disable
