#!/bin/sh

# We want to know when we gained connectivity or when we have an ip-down on internet wan
blink_ipconf()
{
	local wanid=${WANID:-0}
	local internet; eval internet=`cat $WAND/internet 2>/dev/null`

	# If we are called from waneth-up or adsl-up, WANID == 0
	# If we are called from ip-down, we only want internet wan
	[ "$wanid" != 0 ] && [ "$wanid" != "$internet" ] && return

	# We are now trying to get an ip address
	# In WAN bridged mode, do not blink internet LED
	[ "$wanid" = 0 -a ! -f "$BRIDGED/wan$internet" ] && ledctl bflag_ipconf
	[ "$wanid" != 0 -a ! -f "$BRIDGED/wan$wanid" ] && ledctl bflag_ipconf
}

blink_ipconf
