#!/bin/sh

# We want to know when we lost connectivity or when we have an ip-up on internet wan
switch_off_ipconf()
{
	local wanid=${WANID:-0}
	local internet; eval internet=`cat $WAND/internet 2>/dev/null`

	# If we are called from waneth-down or adsl-down, WANID == 0
	# If we are called from ip-up, we only want internet wan
	[ "$wanid" != 0 ] && [ "$wanid" != "$internet" ] && return

	ledctl sflag_ipconf
}

switch_off_ipconf
