#!/bin/sh
# /etc/bewan/scripts/ip-down6-static
# called when going down in static mode
# setparam is already included by calling script

# Environnement variables:

#  IFNAME:  interface name

base_log "$SCRIPTD/ip-down6-static $IFNAME" debug

# Down LAN interface
if [ -f "$INTFD/$IFNAME/lanid" ]; then
  LANID=`cat $INTFD/$IFNAME/lanid`
  base_call_scripts 'ip-down6-lan'

# Down WAN interface
elif [ -f "$INTFD/$IFNAME/wanid" ]; then
  WANID=`cat $INTFD/$IFNAME/wanid`
  base_call_scripts 'ip-down6'
fi
