#!/bin/sh
# /etc/bewan/scripts/ip-down-lan
# included in /etc/bewan/scripts/ip-down-dhcp
# setparam is already included by calling script

# LAN network interface is down

# Save parameters
IFDIR=$LAND/$LANID/ip
if  [ -d "$IFDIR" ]; then
  rm -f $IFDIR/ipaddr
  rm -f $IFDIR/ipmask
  rm -f $IFDIR/routers
  rm -f $IFDIR/servers
fi

# Include scripts found in /etc/bewan/ip-down-lan.d directory
trap base_reboot_on_exit EXIT
for script in `find /etc/bewan/ip-down-lan.d -follow -type f | sort`; do
  base_log "$script $LANID" debug
  . $script $LANID
done
trap '' EXIT
