#!/bin/sh
# Network interface is down (from PPP client)
# Environnement variables:

#  IFNAME:    $1, interface name (pppi)

IFNAME=${1:-}

. /etc/bewan/scripts/globals
. /etc/bewan/lib/base

base_log "$SCRIPTD/ip-down-ppp $IFNAME" debug

# PPP down on WAN interface
[ -f "$INTFD/$IFNAME/wanid" ] || exit 0
WANID=`cat $INTFD/$IFNAME/wanid`

# Take wan-up-down mutex
base_enter_critical 'wan-up-down'

# Get config parameters after taking lock
base_call_initd 'setparam'

# PPP on demand
# Triggers a down / up on the interface
# The SNAT module is listening to this kind of event
# and will flush the conntrack table
if [ -f "$WAND/$WANID/ip/fakeip" ]; then
  ifconfig $IFNAME down up
fi
# Continues with main ip-down script
base_call_scripts 'ip-down'

# Release wan-up-down mutex
base_exit_critical 'wan-up-down'
