#!/bin/sh
# /etc/bewan/scripts/ip-fail6
# included in /etc/bewan/scripts/ip-fail6-dhcp
# included in /etc/bewan/scripts/ip-fail6-ppp
# setparam is already included by calling script

# environment variable
# WANID   wan interface index
# IFFLAGS wan interface flags

WANID=${WANID:-0}

base_log "$SCRIPTD/ip-fail6 $WANID started" debug

# Include scripts found in /etc/bewan/ip-fail6.d directory
trap base_reboot_on_exit EXIT
for script in `find /etc/bewan/ip-fail6.d -follow -type f | sort`; do
  base_log "$script $WANID" debug
  . $script $WANID
done
trap '' EXIT
[ ! -f $RCRUNNING ] && base_call_initd 'inittab'

base_log "$SCRIPTD/ip-fail6 $WANID exited" debug
