#!/bin/sh
# /etc/bewan/scripts/ip-fail
# included in /etc/bewan/scripts/ip-fail-dhcp
# setparam is already included by calling script

# environment variable
# LANID   Lan interface index

LANID=${LANID:-0}

base_log "$SCRIPTD/ip-fail-lan $LANID started" debug

# Include scripts found in /etc/bewan/ip-fail.d directory
trap base_reboot_on_exit EXIT
for script in `find /etc/bewan/ip-fail-lan.d -follow -type f | sort`; do
  base_log "$script $LANID" debug
  . $script $LANID
done
trap '' EXIT
[ ! -f $RCRUNNING ] && base_call_initd 'inittab'

base_log "$SCRIPTD/ip-fail-lan $LANID exited" debug
