#!/bin/sh
# /etc/bewan/init.d/wait-commit

. /etc/bewan/lib/base

base_enter_critical 'store.lock'
base_enter_critical 'save.lock'

# When the two locks are taken we are sure
# that pending commit is terminated

base_exit_critical 'save.lock'
base_exit_critical 'store.lock'
