#!/bin/sh
# /etc/bewan/user.d/diag

# called from /etc/bewan/init.d/users

diag_clean_user() {
	diag_Enable=1
	[ -f $diag_Password ] && rm $diag_Password
}

diag_generate_user() {
	local user="$1" pass="$2" shell='/etc/bewan/scripts/restricted_shell'
	base_log "$userd/diag: $user" debug
	if [ "$user" != "root" ]; then
		echo "$user::0:0:$user:/:$shell" >> $diag_Password
		echo $user:$pass | /usr/sbin/chpasswd >/dev/null
	fi
	return 0
}

local diag_Enable=0
local diag_Password=/var/bewan/passwd
local diag_uid=0

diag_clean_user
