#!/bin/sh
# /etc/bewan/user.d/web

# called from /etc/bewan/init.d/users

web_clean_user() {
	web_Enable=1
	rm -rf $web_dir
}

web_generate_user() {
	local user="$1" pass="$2" group="$3"
	mkdir -p $web_dir
	[ "$pass" = 'EMPTY_PASSWORD' ] && pass=''
	base_log "$userd/web: $user/$group" debug
	echo "$user:$pass" >> "$web_dir/.$group"
	return 0
}

local web_Enable=0
local web_dir=/var/bewan/webuser.d/

web_clean_user
