#!/bin/sh
# /etc/bewan/ip-up-lan.d/S20lanarp
# called from /etc/bewan/scripts/ip-up-lan through sh
# No environement variable
# $LANID = lan interface index

restart_lanarp() {
	local ARG=restart
	base_call_initd 'lanarp'
}

restart_lanarp
