#!/bin/sh

stop_xtm()
{
  local ARG=restart
  local ETHID='all'

  local xdsl_mode=`cat $DSLD/xdslup`
  rm -f $DSLD/xdslup

  if [ "$xdsl_mode" = "adsl" ]; then
    base_call_initd 'ethatm'
  elif [ "$xdsl_mode" = "vdsl" ]; then
    base_call_initd 'ethptm'
  fi
}

stop_xtm

