#!/bin/sh

analyseDHCP43() {
     local index=0

     for i in $DHCP43
     do
          [ "$i" = 1 ] && index=3 && continue
          [ "$i" = 2 ] && index=4 && continue

          [ $index -eq 3 ] && option43part1="1,$i" && index=0
          [ $index -eq 4 ] && option43part2="2,$i" && index=0
     done
}

AnalyzeDHCP125() {
    local oui serialnumber productclass
    local entreprisenb=${1:-}
    local nb_args=$#

    if [ "$nb_args" -lt "7" ]; then
       base_log "S50-gvtSTB: $nb_args args is not enough" debug
       echo ""
       return
    fi
    shift 1

    # Parse all vendor options
    while [ "${1:-}" != "" ]
    do
        local code=${1:-}
        shift 1
        local value=${1:-}
        shift 1

        # Code 1 : Device Manufacturer OUI
        if [ "$code" = "1" ]; then
            if [ "$value" != "" ]; then
                oui=$value
            fi
        # Code 2 : Device Serial Number
        elif [ "$code" = "2" ]; then
            if [ "$value" != "" ]; then
                serialnumber=$value
            fi
        # Code 3 : Device Product Class
        elif [ "$code" = "3" ]; then
            if [ "$value" != "" ]; then
                productclass=$value
            fi
        fi
    done

    if [ "${entreprisenb:-}" != "" ] && [ "${oui:-}" != "" ] && [ "${serialnumber:-}" != "" ] && [ "${productclass:-}" != "" ]; then
        echo "$entreprisenb,$oui,$serialnumber,$productclass"
    else
        echo ""
    fi
}

restart_gvtSTB() {
     local wanid=${WANID:-0}

     [ "$wanid" != 3 ] && return 0

     local new_ntp_servers option100 option101 new_dns_servers option125

     new_ntp_servers=`echo ${ntpsrv:-} | sed -e 's/ /,/g'`
     new_dns_servers=`echo ${SERVERS:-}  | sed -e 's/ /,/g'`
     option100="${DHCP100:-}"
     option101="${DHCP101:-}"
     option125=''
     [ "${DHCP125:-}" != "" ] && option125=$(AnalyzeDHCP125 ${DHCP125})

     local needUpdate=0;
     local option43part1=''
     local option43part2=''

     analyseDHCP43
     # Clear DHCP43 variable to prevent treatment in DHCP43 script
     DHCP43=''

     [ "$new_ntp_servers" != "${LANDevice_1_HostConfig_DHCPOptions_1_Value:-}" ] && needUpdate=1
     [ "$option101" != "${LANDevice_1_HostConfig_DHCPOptions_2_Value:-}" ] && needUpdate=1
     [ "$option43part1" != "${LANDevice_1_HostConfig_DHCPOptions_3_Value:-}" ] && needUpdate=1
     [ "$option43part2" != "${LANDevice_1_HostConfig_DHCPOptions_4_Value:-}" ] && needUpdate=1
     [ "$option100" != "${LANDevice_1_HostConfig_DHCPOptions_5_Value:-}" ] && needUpdate=1
     [ "$new_dns_servers" != "${LANDevice_1_HostConfig_DHCPOptions_6_Value:-}" ] && needUpdate=1
     [ "$option125" != "${LANDevice_1_HostConfig_DHCPOptions_7_Value:-}" ] && needUpdate=1

     [ $needUpdate -eq 0 ] && return 0

     local ntpServerEnable=1
     local option101Enable=1
     local option43part1Enable=1
     local option43part2Enable=1
     local option100Enable=1
     local dnsServerEnable=1
     local option125Enable=1

     [ "$new_ntp_servers" = "" ] && ntpServerEnable=0
     [ "$option101" = "" ] && option101Enable=0
     [ "$option43part1" = "" ] && option43part1Enable=0
     [ "$option43part2" = "" ] && option43part2Enable=0
     [ "$option100" = "" ] && option100Enable=0
     [ "$new_dns_servers" = "" ] && dnsServerEnable=0
     [ "$option125" = "" ] && option125Enable=0

     # Tell script S99-gvtSTB to wait a little before removing netfilter rule
     touch $WAND/$wanid/dhcp-changed
     # Apply configuration changes
     (
     cli -s <<EOF

cd _LANDevice_1_HostConfig_DHCPOptions
reset 0

mk 1
set Enable $ntpServerEnable
set Name ntp-server
set Forced 0
set Value $new_ntp_servers
set MatchName stb-user
cd ..

mk 2
set Enable $option101Enable
set Name t-code
set Forced 0
set Value $option101
set MatchName stb-user
cd ..

mk 3
set Enable $option43part1Enable
set Name 'vendor:dslforum.org'
set Forced 0
set Value $option43part1
set MatchName stb-user
cd ..

mk 4
set Enable $option43part2Enable
set Name 'vendor:dslforum.org'
set Forced 0
set Value $option43part2
set MatchName stb-vendor
cd ..

mk 5
set Enable $option100Enable
set Name ieee10031
set Forced 0
set Value $option100
set MatchName stb-user
cd ..

mk 6
set Enable $dnsServerEnable
set Name dns-server
set Forced 0
set Value $new_dns_servers
set MatchName stb-user
cd ..

mk 7
set Enable $option125Enable
set Name vendor-id-spec
set Forced 0
set Value $option125
set MatchName stb-user
cd ..

fcommit
EOF
     ) &
}

restart_gvtSTB

