#!/bin/sh

# Called on ip-up event on a WAN interface
# $WANID, WAN interface index
# $DEFRTE, set to 1 if WAN is a default route
# $INET, set to 1 if WAN is an Internet connection
start_dyndns() {
	local dyndnscmd
	[ "$INET" != 1 ] && return

	# launch all prepared dyndns account refresh scripts for this wan
	for dyndnscmd in `ls /var/bewan/dyndns.d/dyndns-*.sh 2>/dev/null`; do
		start-stop-daemon -S -b -x $dyndnscmd -- $WANID
	done
}

start_dyndns
