#!/bin/sh

# Called on ip-up event on a WAN interface
# $WANID, WAN interface index
# $DEFRTE, set to 1 if WAN is a default route
# $INET, set to 1 if WAN is an Internet connection
restart_ntp() {
	# Sanity check on NTP command
	local ntpcmd=/var/bewan/ntp.d/ntp.sh
	[ ! -f $ntpcmd ] && return

	# Sanity check on interface type
	if [ "${Services_Time_NTPInterfaceType:-}" != "WANConnectionDevice" ]; then
		return
	fi

	# Sanity check on interface
	local wanid=$WANID; [ "$wanid" = '' ] && return

	# Specific wan interface ?
	local iface=`cat /var/bewan/ntp.d/interface 2>/dev/null`
	if [ "$iface" = '' ]; then
		# Use Internet interface
		[ "$INET" != 1 ] && return
	else 
		# Use specific interface
		local ok=0
		local i
		for i in `strip $iface`; do
			[ "$i" = "$wanid" ] && ok=1
		done
		[ "$ok" = 0 ] && return
	fi

	# Execute NTP request in background
	start-stop-daemon -S -b -x $ntpcmd -- wan $wanid
}

restart_ntp
