#!/bin/sh

# Called on ip-up event on a WAN interface
# $WANID, WAN interface index
# $DEFRTE, set to 1 if WAN is a default route
# $INET, set to 1 if WAN is an Internet connection
restart_webauth() {
	# Refresh last modification time of webauth.conf
	# to force a rescan the configuration
	conf='/var/bewan/webauth.conf'
	if [ -f $conf ]; then
		touch $conf
	fi
}

restart_webauth
