#!/bin/sh

# Called on ip-up event on a WAN interface
# $WANID, WAN interface index
# $DEFRTE, set to 1 if WAN is a default route
# $INET, set to 1 if WAN is an Internet connection

remove_stb_filter() {
  # Select interface WAN3 (VoD)
  [ "${WANID:-0}" != 3 ] && return

  rm -f $NFDYND/filter/input/00-gvtSTB
  base_call_initd 'fwdynamic'
}

(
  # Wait a little to allow lan dhcp server to restart
  [ -f "$WAND/$WANID/dhcp-changed" ] && sleep 10
  rm -f "$WAND/$WANID/dhcp-changed"
  # Remove netfilter rule
  remove_stb_filter
) &
