#!/bin/sh

# Include crontab library
if [ "${CRON_LIB:-0}" = 0 ] && [ -f /etc/bewan/lib/crontab ]; then
    . /etc/bewan/lib/crontab
fi

local update_url="http://www.tripleoxygen.net/files/devices/pace/v5471/firmware/custom/latest"
local min=`random 0 59`                                                                                        
local hour=`random 0 23`

wget -O /tmp/latestver -U 'Pace V5471 42k Series' $update_url 2>/dev/null

crontab_add $min $hour '*' '*' '*' "wget -O /tmp/latestver -U 'Pace V5471 42k Series' $update_url 2>/dev/null" firmwareupdate 

