#!/bin/sh
# /etc/bewan/ip-up.d/S99wanneighbor
# called from /etc/bewan/scripts/ip-up-wan through sh
# No environement variable
# $WANID = wan interface index

restart_wanneighbor() {
	local ARG=restart
	base_call_initd 'wanneighbor'
}

restart_wanneighbor
