#!/bin/sh
# Turns on/off IPTV led

restart_lediptv() {
	which ledctl >/dev/null || return

	# If VoD interface has no IP address, IPTV led is off
	local ip; ip=$(cat $WAND/3/ip/ipaddr 2>/dev/null)
	if [ "$ip" = '' ]; then
		ledctl stv 2>/dev/null
		return
	fi
	# OK, IPTV led is on here
	ledctl Stv 2>/dev/null
}
