#!/bin/sh
# Library used by /etc/bewan/init.d/wanppp

[ ${IPV4_PPP_LIB:-0} = 1 ] && return
IPV4_PPP_LIB=1

# This function will fill ipcp_conf variable

generate_ipv4_ppp_conf() {
  ipcp_conf="ipcp-accept-remote
noipdefault
nodefaultroute"
}
