#!/bin/sh
# Library used by /etc/bewan/init.d/wanppp

[ ${IPV6_PPP_LIB:-0} = 1 ] && return
IPV6_PPP_LIB=1

# This function will fill ipv6cp_conf variable

generate_ipv6_ppp_conf() {
  ipv6cp_conf="+ipv6
ipv6cp-use-persistent"
}
