#!/bin/sh
# vim: set ts=2 sw=2 et:
# /etc/bewan/lib/modem

# specific vendor functions used by modem scripts
# setparam must be included


if [ ${MODEM_LIB_LOADED:-0} -eq 1 ]; then
  return
fi

MODEM_LIB_LOADED=1

# TODO: Include functions used by hotmodem and modem scripts here