#!/bin/sh
# /etc/bewan/lib/wifissid

# specific vendor functions used by wifi scripts
# setparam must be included
# used to modify the SSID of the gateway

# Working variables
# $ETHID: WLANInterface index
# $ifname: name of wifi network interface
# $WIFID/$ifname: working directory of WIFI interface

if [ ${WIFI_LIB_LOADED:-0} -eq 1 ]; then
  return
fi

BCMINITRUNNING=
if base_enter_critical 'bcmwl-init' 'nowait'; then
  base_exit_critical 'bcmwl-init'
else
  BCMINITRUNNING=1
fi

# Uncomment the echo to debug commands
exec_cmd() {
#  echo $1 | base_log - debug
  $1 >/dev/null 2>/dev/null
}

# Allow editing ssid#.conf file with special characters
ssid_conf_set_ascii() {
  # Delete the line
  sed -i "/$1/d" $WIFID/ssid$ETHID.conf
  # Add the line
  echo "$1=$2" >> $WIFID/ssid$ETHID.conf
}

restart_vendor_wifi() {
  # SSID
  local ssid; eval ssid=\${'WLANInterface_'$ETHID'_Config_SSID'}
  ssid_conf_set_ascii wlSsid "$ssid"
  ssid_conf_set_ascii wlWscRestart Y
  # Start the wlmng, it might not be the fastest if we just want to change the SSID
  [ -z "$BCMINITRUNNING" ] && /bin/wlmngr 2>&1 1>/dev/null
}

WIFI_LIB_LOADED=1
