#!/bin/sh

set_wan_gvt() {
  # Set INFACTORY, so that gvt script won't fcommit
  local INFACTORY=1

  [ ! -f /nvram/gvt/wanethmode ] && {
    mkdir -p /nvram/gvt
    # The default value is also set in action library
    # If you change it here, please check src directory
    echo -n Default > /nvram/gvt/wanethmode
  }
  base_call_scripts 'gvt-wan-mode'
}

set_wan_gvt
