#!/bin/sh

base_log "GVT Setting default wireless configuration" debug

# Get 4 last hexadecimal digits of RF MAC address
local macext=`pzinfo wanmac | sed -e 's/^\([^:]*\):\([^:]*\):\([^:]*\):\([0-9a-fA-F]\)\([0-9a-fA-F]\):\([^:]*\):\([^:]*\)/\6\7/'`
local ssid_name="GVT-${macext}"

local SERIAL=`pzinfo serial`
local SERIAL_10END=`echo $SERIAL | cut -c$((${#SERIAL} - 9))-${#SERIAL}`

cli -q <<EOF
  cd _WLANInterface_1_Config
  sset SSID $ssid_name
  sset WPADefaultKey $SERIAL_10END
  sset WEPKey1 $SERIAL_10END
EOF
