#!/bin/sh
# 

# load setparam
. /etc/bewan/init.d/setparam

ippos_printer_up()
{
	local myaction=${1:-"nothing"}

	case "$myaction" in
		add|remove|update)
			# update printer
			local ARG=restart
			base_call_initd "ippos.init"
		;;
		*)
		  base_log "Action $myaction dropped." debug
		;;
	esac
}

ippos_printer_up ${1:-}

