#!/bin/sh

# Called on ip-up event on a WAN interface
# $WANID, WAN interface index

if [ "${CRON_LIB:-0}" = 0 ] && [ -f /etc/bewan/lib/crontab ]; then
	. /etc/bewan/lib/crontab
fi

if [ "${CRON_LIB:-0}" = 0 ]; then
	echo "Cron Library Does not Exists !"
	return 1
fi

stop_crontab_gre(){
  local wanid=${WANID:-0}
  if [ "$wanid" = 1 ]; then
    #remove cron
    crontab_remove gre_tunnel_mngt
    wl -i $WLANInterface_2_Ifname ssid ""    
  fi
}

stop_crontab_gre
