#!/bin/sh
# Start other services

. /etc/bewan/scripts/globals
. /etc/bewan/lib/base

# Take onchange mutex (used by configd, adsl-up...)
base_enter_critical 'onchange'

# Get config parameters after taking lock
base_call_initd 'setparam'

ARG=start
for script in `find /etc/bewan/rc2.d -follow -type f | sort`; do
  . $script
done
base_call_initd 'inittab'

# Release onchange mutex
base_exit_critical 'onchange'

base_log "rc2 complete" notice
rm $RC2RUNNING
