#!/bin/sh
# Called by waneth-up.d
# $1 : up
# $2 : WANETHID

WANETHID=${WANETHID:-}
if [ "$WANETHID" = '' ]; then
  WANETHID=${2:-}
fi

base_log "S00-0-start-waneth ${1:-} ${2:-}"

start_waneth()
{
  local ARG=restart
  base_call_initd 'wanethernet'
}

start_waneth

