#!/bin/sh

# Read hardware boot status and increment persistent watchdog counter
watchdog_bootstatus()
{
  local status=`cat /proc/watchdog/boot_status`
  if [ "$status" = 1 ]; then
    local count=$(( ${Device_Watchdog_RebootCounter:-0} + 1 ))
    echo "cd _Device_Watchdog; sset RebootCounter $count; fcommit" | cli -q
  else
    status=0
  fi
  echo $status
  return 0
}

# Set watrchdog timer margin in seconds
watchdog_setmargin()
{
  local secs=${1:-180}
  local margin=`cat /proc/watchdog/soft_margin`
  local periods=$(( $secs /  $margin ))
  echo $periods >/proc/watchdog/soft_periods
}

if [ "$Device_Watchdog_Enable" != 1 ]; then
  BOOTSTATUS=0
  return
fi

modprobe softdog_hal
modprobe softdog

# Record persistent watchdog counter
BOOTSTATUS=$( watchdog_bootstatus )
# Increase watchdog margin to 180 seconds during boot
watchdog_setmargin 180
# Start watchdog daemon
base_add_daemon 'wdgd' '/sbin/wdgd'
