#!/bin/sh

# Force manual mode for FAP port 12 (HPNA port) for TMII
export LD_LIBRARY_PATH=/lib/public:/lib/private:/lib/gpl:/lib

fap tm --type --if eth5 --lan
# port rate is 200Mbit/s * 99%
fap tm --ifcfg --if eth5 --manual --kbps 198000 --mbs 2000
fap tm --mode --if eth5 --manual
fap tm --apply --if eth5  --enable
fap tm --if eth5 --tmq2swq --queue 0 --swqueue 0
fap tm --if eth5 --tmq2swq --queue 1 --swqueue 1
fap tm --if eth5 --tmq2swq --queue 2 --swqueue 2
fap tm --if eth5 --tmq2swq --queue 3 --swqueue 3


# Enable pause between HPNA coppergate chip and BCM63168
switchctl bcm63168 broadcom_ubus -s 0x28:4=0x802010
