#!/bin/sh

# Called on ip-up event on a LAN interface
# $LANID, LAN interface index

export LD_LIBRARY_PATH=/lib/public:/lib/private:/lib/gpl:/lib

# run the command given as parameter
execute() {
  local res;
  eval $1
  res=$?
  debug_log "$1" "$res"
  return $res
}

debug_log() {
  local dbg;eval dbg=\${'QueueManagement_Debug':-}
  local message="Successful"
  [ $2 -ne 0 ] &&  message="Fail ret=$2"
  [ "x$dbg" = "x1" ] && base_log "[$1] [$message]" debug
}


setLan_and_setSpeed_intf() {
	local switchid; switchid=0
	local found; found=0
	while [ $switchid -lt ${Switch_Count:-0} -a $found -lt 1 ]
	do
		switchid=$(($switchid + 1))
		eval portlist=\${'Switch_'$switchid'_Port_List':-}
		for portlistid in `strip $portlist`; do
			local port_en; eval port_en=\${'Switch_'$switchid'_Port_'$portlistid'_Enable':-0}
			[ $port_en != 1 ] && continue
			local LANIdx; eval LANIdx=\${'Switch_'$switchid'_Port_'$portlistid'_LANEthernetInterfaceIdx':-'NotLan'}
			local WANIdx; eval WANIdx=\${'Switch_'$switchid'_Port_'$portlistid'_WANEthernetInterfaceIdx':-'NotWan'}
			local lan_en; eval lan_en=\${'LANEthernetInterface_'$LANIdx'_Enable':-}
			[ "$lan_en" = "0" ] && continue # Lan is not Enable
			
			if [ "$LANIdx" != "NotLan" -a "$WANIdx" = "NotWan" ]; then
				local lan_ifname; eval lan_ifname=\${'LANEthernetInterface_'$LANIdx'_Ifname':-}
				execute "fap tm --apply --if $lan_ifname  --disable"
				execute "fap tm --type --if $lan_ifname --lan"
				execute "fap tm --mode --if $lan_ifname --manual"
				#Force the Port rate at 1Gbit * 99%
				execute "fap tm --ifcfg --if $lan_ifname --manual --kbps 990000 --mbs 2000 --rate"
				execute "fap tm --apply --if $lan_ifname  --enable"
				execute "fap tm --if $lan_ifname --tmq2swq --queue 0 --swqueue 0"
				execute "fap tm --if $lan_ifname --tmq2swq --queue 1 --swqueue 1"
				execute "fap tm --if $lan_ifname --tmq2swq --queue 2 --swqueue 2"
				execute "fap tm --if $lan_ifname --tmq2swq --queue 3 --swqueue 3"
			fi
		done
	done
}

setLan_and_setSpeed_intf
