#!/bin/sh
# Called from /etc/bewan/rc
# Restart each port of the switch to force a new negociation.

main_start_phy() {
  local SWITCHID='all'
  local PORTID='all'
  base_call_initd "phy"
}

main_start_phy
