#!/bin/sh
# Called by waneth-down.d
# $1 : up
# $2 : WANETHID

WANETHID=${WANETHID:-}
if [ "$WANETHID" = '' ]; then
  WANETHID=${2:-}
fi

stop_waneth()
{
  local ARG=restart
  base_call_initd 'wanethernet'
}

stop_waneth

