#!/bin/sh
# /etc/bewan/ip-up6-lan.d/S01sroutes
# called from /etc/bewan/scripts/ip-up6-lan through sh
# No environement variable
# $LANID = lan interface index

# Brings-up LAN static routes
ipup6_lan_static_routes() {
  local ifname=`cat $LAND/$LANID/ifname 2>/dev/null`
  [ "$ifname" = '' ] && return
  local routers=`cat $LAND/$LANID/ip6/routers 2>/dev/null`
  local i dest gate router

  if  [ -d "$ROUTE6D/lan$LANID" ]; then
    for i in `ls $ROUTE6D/lan$LANID`; do
      dest=`cat $ROUTE6D/lan$LANID/$i/dest 2>/dev/null`
      gate=`cat $ROUTE6D/lan$LANID/$i/gate 2>/dev/null`
      for router in $routers; do
        [ "$gate" = '' ] && GATE="via $router"
      done
      if [ "$dest" != '' ]; then
        ip -6 route add $dest $gate dev $ifname table $i 2>&1 | base_log - debug
      fi
    done
  fi
}

ipup6_lan_static_routes
