#!/bin/sh
# /etc/bewan/ip-up6-lan.d/S20lanndp
# called from /etc/bewan/scripts/ip-up6-lan through sh
# No environement variable
# $LANID = lan interface index

restart_lanndp() {
	local ARG=restart
	base_call_initd 'lanndp'
}

restart_lanndp
