#!/bin/sh

# Included to retrieve dsl state
. /etc/bewan/lib/libdsl

start_xtm()
{
  mkdir -p $DSLD

  local ARG=restart
  local ETHID='all'

  local xdsl_mode
  retrieve_xdsl_mode

  echo "$xdsl_mode" > $DSLD/xdslup

  if [ "$xdsl_mode" = "adsl" ]; then
    base_call_initd 'ethatm'
  elif [ "$xdsl_mode" = "vdsl" ]; then
    base_call_initd 'ethptm'
  fi
}

start_xtm

