#!/bin/ash
# 42k Series (C) 2016 Triple Oxygen

export LD_LIBRARY_PATH=/lib/public:/lib/private:/lib/gpl:/lib

# Include crontab library
if [ "${CRON_LIB:-0}" = 0 ] && [ -f /etc/bewan/lib/crontab ]; then
    . /etc/bewan/lib/crontab
fi

UPDATE_PERIOD=1
GRAPH_PERIOD=5
DATA_PATH=/tmp/stats_data
STATS_PATH=/tmp/stats
BINNUM=$(xdslctl info --SNR | tail -n +9 | wc -l)

if [ ! -d "$STATS_PATH" ]; then
    mkdir "$STATS_PATH"
fi

/etc/bewan/scripts/stats/update-webstats "$STATS_PATH"

if [ ! -f "/nvram/disable_stats" ]; then

    if [ ! -d "$DATA_PATH" ]; then
        mkdir "$DATA_PATH"
        /etc/bewan/scripts/stats/init.sh "$DATA_PATH"
    fi

    if [ ${CRON_LIB:-0} = 1 ]; then
        crontab_add "*/${UPDATE_PERIOD}" '*' '*' '*' '*' "/etc/bewan/scripts/stats/update.sh '$DATA_PATH'" stats_update
        crontab_add "*/${GRAPH_PERIOD}" '*' '*' '*' '*' "/etc/bewan/scripts/stats/graph.sh '$DATA_PATH' '$STATS_PATH' '$BINNUM'" stats_graph
    fi
fi

